//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_ff_problem_finished {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_otd_ff_facility_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_ind_hydrant_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_extinguisher_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_maintain_repl_ff_pipe_len;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ff_aisle_reform_len;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ff_aisle_reform_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ff_aisle_remove_len;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_rep_repl_otd_ff_facil_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_fire_brigade_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_fire_brigade_level;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_ff_aisle_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_ff_aisle_len;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txttciunset10;
		protected global::System.Web.UI.WebControls.TextBox txttciunset11;
		protected global::System.Web.UI.WebControls.TextBox txttciunset12;
		protected global::System.Web.UI.WebControls.TextBox txttciunset13;
		protected global::System.Web.UI.WebControls.TextBox txttciunset14;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
