//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_ff_problem_finished {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_otd_ff_facility_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_ind_hydrant_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_extinguisher_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_maintain_repl_ff_pipe_len;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ff_aisle_reform_len;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ff_aisle_reform_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ff_aisle_remove_len;
	protected global::System.Web.UI.WebControls.Label lblcommunity_rep_repl_otd_ff_facil_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fire_brigade_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fire_brigade_level;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_ff_aisle_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_ff_aisle_len;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbltciunset11;
	protected global::System.Web.UI.WebControls.Label lbltciunset12;
	protected global::System.Web.UI.WebControls.Label lbltciunset13;
	protected global::System.Web.UI.WebControls.Label lbltciunset14;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
