//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_elec_supply {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_load_dispatching_office_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_transformer_num;
		protected global::System.Web.UI.WebControls.TextBox txtbelow_100kva_transformer_num;
		protected global::System.Web.UI.WebControls.TextBox txtat_100_500kva_transformer_num;
		protected global::System.Web.UI.WebControls.TextBox txtat_500_1000kva_transformer_num;
		protected global::System.Web.UI.WebControls.TextBox txtmore_1000kva_transformer_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_elec_supply_wireways_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_power_transmission_line_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_high_voltage_distr_line_legth;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_low_voltage_distr_line_legth;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_elec_supply_consumption;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_resident_elec_consumption;
		protected global::System.Web.UI.WebControls.TextBox txtno_elec_days;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcesunset13;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
