//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_elec_supply {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_load_dispatching_office_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_transformer_num;
	protected global::System.Web.UI.WebControls.Label lblbelow_100kva_transformer_num;
	protected global::System.Web.UI.WebControls.Label lblat_100_500kva_transformer_num;
	protected global::System.Web.UI.WebControls.Label lblat_500_1000kva_transformer_num;
	protected global::System.Web.UI.WebControls.Label lblmore_1000kva_transformer_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_elec_supply_wireways_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_power_transmission_line_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_high_voltage_distr_line_legth;
	protected global::System.Web.UI.WebControls.Label lblcommunity_low_voltage_distr_line_legth;
	protected global::System.Web.UI.WebControls.Label lblcommunity_elec_supply_consumption;
	protected global::System.Web.UI.WebControls.Label lblcommunity_resident_elec_consumption;
	protected global::System.Web.UI.WebControls.Label lblno_elec_days;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcesunset1;
	protected global::System.Web.UI.WebControls.Label lbltcesunset2;
	protected global::System.Web.UI.WebControls.Label lbltcesunset3;
	protected global::System.Web.UI.WebControls.Label lbltcesunset4;
	protected global::System.Web.UI.WebControls.Label lbltcesunset5;
	protected global::System.Web.UI.WebControls.Label lbltcesunset6;
	protected global::System.Web.UI.WebControls.Label lbltcesunset7;
	protected global::System.Web.UI.WebControls.Label lbltcesunset8;
	protected global::System.Web.UI.WebControls.Label lbltcesunset9;
	protected global::System.Web.UI.WebControls.Label lbltcesunset10;
	protected global::System.Web.UI.WebControls.Label lbltcesunset11;
	protected global::System.Web.UI.WebControls.Label lbltcesunset12;
	protected global::System.Web.UI.WebControls.Label lbltcesunset13;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
