//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_geologic_hazard {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtserious_geologic_hazard_num;
		protected global::System.Web.UI.WebControls.TextBox txtserious_geologic_hazard_handle_num;
		protected global::System.Web.UI.WebControls.TextBox txtinfluence_house_area;
		protected global::System.Web.UI.WebControls.TextBox txtprotect_house_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcghunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcghunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcghunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcghunset4;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
