//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_geologic_hazard {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblserious_geologic_hazard_num;
	protected global::System.Web.UI.WebControls.Label lblserious_geologic_hazard_handle_num;
	protected global::System.Web.UI.WebControls.Label lblinfluence_house_area;
	protected global::System.Web.UI.WebControls.Label lblprotect_house_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcghunset1;
	protected global::System.Web.UI.WebControls.Label lbltcghunset2;
	protected global::System.Web.UI.WebControls.Label lbltcghunset3;
	protected global::System.Web.UI.WebControls.Label lbltcghunset4;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
