//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_fire_fighting {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_extinguisher_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_good_extinguisher_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_hydrant_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ots_hydrant_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_good_ots_hydrant_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ind_hydrant_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_good_ind_hydrant_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ff_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ff_pipe_caliber_larger_than_100mm_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ff_pipe_caliber_less_than_100mm_length;
		protected global::System.Web.UI.WebControls.TextBox txtsource_of_ff_water_num;
		protected global::System.Web.UI.WebControls.TextBox txtnatural_ff_water_source_num;
		protected global::System.Web.UI.WebControls.TextBox txtmunicipal_administration_pipe_net_ff_water_source;
		protected global::System.Web.UI.WebControls.TextBox txtff_water_pool_num;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset13;
		protected global::System.Web.UI.WebControls.TextBox txttcffunset14;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
