//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_fire_fighting {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_extinguisher_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_good_extinguisher_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_hydrant_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ots_hydrant_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_good_ots_hydrant_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ind_hydrant_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_good_ind_hydrant_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ff_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ff_pipe_caliber_larger_than_100mm_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ff_pipe_caliber_less_than_100mm_length;
	protected global::System.Web.UI.WebControls.Label lblsource_of_ff_water_num;
	protected global::System.Web.UI.WebControls.Label lblnatural_ff_water_source_num;
	protected global::System.Web.UI.WebControls.Label lblmunicipal_administration_pipe_net_ff_water_source;
	protected global::System.Web.UI.WebControls.Label lblff_water_pool_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcffunset1;
	protected global::System.Web.UI.WebControls.Label lbltcffunset2;
	protected global::System.Web.UI.WebControls.Label lbltcffunset3;
	protected global::System.Web.UI.WebControls.Label lbltcffunset4;
	protected global::System.Web.UI.WebControls.Label lbltcffunset5;
	protected global::System.Web.UI.WebControls.Label lbltcffunset6;
	protected global::System.Web.UI.WebControls.Label lbltcffunset7;
	protected global::System.Web.UI.WebControls.Label lbltcffunset8;
	protected global::System.Web.UI.WebControls.Label lbltcffunset9;
	protected global::System.Web.UI.WebControls.Label lbltcffunset10;
	protected global::System.Web.UI.WebControls.Label lbltcffunset11;
	protected global::System.Web.UI.WebControls.Label lbltcffunset12;
	protected global::System.Web.UI.WebControls.Label lbltcffunset13;
	protected global::System.Web.UI.WebControls.Label lbltcffunset14;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
