//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_commerce {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_come_fac_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_come_fac_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_come_fac_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_come_enp_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_come_enp_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_come_enp_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_emporium_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_small_supermarket_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_CVS_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_restauran_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_household_appliances_store_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_agricultural_production_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_clothes_store_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_hardware_building_materials_store_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_drugstore_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_bookstore_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_other_come_enp_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farm_produce_fair_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farm_produce_fair_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farm_produce_fair_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farm_produce_fair_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pedlar_market_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pedlar_market_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pedlar_market_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pedlar_market_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farm_whs_market_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farm_whs_market_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farm_whs_market_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farm_whs_market_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttccunset1;
		protected global::System.Web.UI.WebControls.TextBox txttccunset2;
		protected global::System.Web.UI.WebControls.TextBox txttccunset3;
		protected global::System.Web.UI.WebControls.TextBox txttccunset4;
		protected global::System.Web.UI.WebControls.TextBox txttccunset5;
		protected global::System.Web.UI.WebControls.TextBox txttccunset6;
		protected global::System.Web.UI.WebControls.TextBox txttccunset7;
		protected global::System.Web.UI.WebControls.TextBox txttccunset8;
		protected global::System.Web.UI.WebControls.TextBox txttccunset9;
		protected global::System.Web.UI.WebControls.TextBox txttccunset10;
		protected global::System.Web.UI.WebControls.TextBox txttccunset11;
		protected global::System.Web.UI.WebControls.TextBox txttccunset12;
		protected global::System.Web.UI.WebControls.TextBox txttccunset13;
		protected global::System.Web.UI.WebControls.TextBox txttccunset14;
		protected global::System.Web.UI.WebControls.TextBox txttccunset15;
		protected global::System.Web.UI.WebControls.TextBox txttccunset16;
		protected global::System.Web.UI.WebControls.TextBox txttccunset17;
		protected global::System.Web.UI.WebControls.TextBox txttccunset18;
		protected global::System.Web.UI.WebControls.TextBox txttccunset19;
		protected global::System.Web.UI.WebControls.TextBox txttccunset20;
		protected global::System.Web.UI.WebControls.TextBox txttccunset21;
		protected global::System.Web.UI.WebControls.TextBox txttccunset22;
		protected global::System.Web.UI.WebControls.TextBox txttccunset23;
		protected global::System.Web.UI.WebControls.TextBox txttccunset24;
		protected global::System.Web.UI.WebControls.TextBox txttccunset25;
		protected global::System.Web.UI.WebControls.TextBox txttccunset26;
		protected global::System.Web.UI.WebControls.TextBox txttccunset27;
		protected global::System.Web.UI.WebControls.TextBox txttccunset28;
		protected global::System.Web.UI.WebControls.TextBox txttccunset29;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
