//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_commerce {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_come_fac_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_come_fac_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_come_fac_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_come_enp_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_come_enp_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_come_enp_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_emporium_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_small_supermarket_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_CVS_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_restauran_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_household_appliances_store_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_agricultural_production_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_clothes_store_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_hardware_building_materials_store_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_drugstore_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_bookstore_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_other_come_enp_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farm_produce_fair_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farm_produce_fair_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farm_produce_fair_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farm_produce_fair_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pedlar_market_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pedlar_market_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pedlar_market_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pedlar_market_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farm_whs_market_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farm_whs_market_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farm_whs_market_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farm_whs_market_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltccunset1;
	protected global::System.Web.UI.WebControls.Label lbltccunset2;
	protected global::System.Web.UI.WebControls.Label lbltccunset3;
	protected global::System.Web.UI.WebControls.Label lbltccunset4;
	protected global::System.Web.UI.WebControls.Label lbltccunset5;
	protected global::System.Web.UI.WebControls.Label lbltccunset6;
	protected global::System.Web.UI.WebControls.Label lbltccunset7;
	protected global::System.Web.UI.WebControls.Label lbltccunset8;
	protected global::System.Web.UI.WebControls.Label lbltccunset9;
	protected global::System.Web.UI.WebControls.Label lbltccunset10;
	protected global::System.Web.UI.WebControls.Label lbltccunset11;
	protected global::System.Web.UI.WebControls.Label lbltccunset12;
	protected global::System.Web.UI.WebControls.Label lbltccunset13;
	protected global::System.Web.UI.WebControls.Label lbltccunset14;
	protected global::System.Web.UI.WebControls.Label lbltccunset15;
	protected global::System.Web.UI.WebControls.Label lbltccunset16;
	protected global::System.Web.UI.WebControls.Label lbltccunset17;
	protected global::System.Web.UI.WebControls.Label lbltccunset18;
	protected global::System.Web.UI.WebControls.Label lbltccunset19;
	protected global::System.Web.UI.WebControls.Label lbltccunset20;
	protected global::System.Web.UI.WebControls.Label lbltccunset21;
	protected global::System.Web.UI.WebControls.Label lbltccunset22;
	protected global::System.Web.UI.WebControls.Label lbltccunset23;
	protected global::System.Web.UI.WebControls.Label lbltccunset24;
	protected global::System.Web.UI.WebControls.Label lbltccunset25;
	protected global::System.Web.UI.WebControls.Label lbltccunset26;
	protected global::System.Web.UI.WebControls.Label lbltccunset27;
	protected global::System.Web.UI.WebControls.Label lbltccunset28;
	protected global::System.Web.UI.WebControls.Label lbltccunset29;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
