//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_sanitation_problem_finished {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_ashbin_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_dustbin_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_waste_transfer_station_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_waste_transfer_station_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_ashbin_dustbin_num;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_num_f_update;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_area_f_update;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
