//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_service {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_comm_serv_fac_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_comm_serv_fac_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_comm_serv_cen_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_comm_serv_cen_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_comm_serv_cen_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_empm_supt_cen_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_empm_supt_cen_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_empm_supt_cen_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_police_sta_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_police_sta_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_police_sta_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prop_magm_unit_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_no_prop_magm_unit_num;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcsrunset13;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
