//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_service {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_comm_serv_fac_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_comm_serv_fac_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_comm_serv_cen_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_comm_serv_cen_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_comm_serv_cen_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_empm_supt_cen_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_empm_supt_cen_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_empm_supt_cen_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_police_sta_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_police_sta_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_police_sta_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prop_magm_unit_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_no_prop_magm_unit_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset1;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset2;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset3;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset4;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset5;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset6;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset7;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset8;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset9;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset10;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset11;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset12;
	protected global::System.Web.UI.WebControls.Label lbltcsrunset13;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
