//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.enterprise {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtid;
		protected global::System.Web.UI.WebControls.TextBox txtcounty;
		protected global::System.Web.UI.WebControls.TextBox txtcommunty;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtaddress;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_community;
		protected global::System.Web.UI.WebControls.TextBox txttype;
		protected global::System.Web.UI.WebControls.TextBox txtmain_product;
		protected global::System.Web.UI.WebControls.TextBox txtarea;
		protected global::System.Web.UI.WebControls.TextBox txtstuff_amount;
		protected global::System.Web.UI.WebControls.TextBox txtimmigrant_stuff_amount;
		protected global::System.Web.UI.WebControls.TextBox txtlf_average_salary;
		protected global::System.Web.UI.WebControls.TextBox txtnote_information;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtteunset1;
		protected global::System.Web.UI.WebControls.TextBox txtteunset2;
		protected global::System.Web.UI.WebControls.TextBox txtteunset3;
		protected global::System.Web.UI.WebControls.TextBox txtteunset4;
		protected global::System.Web.UI.WebControls.TextBox txtteunset5;
		protected global::System.Web.UI.WebControls.TextBox txtteunset6;
		protected global::System.Web.UI.WebControls.TextBox txtteunset7;
		protected global::System.Web.UI.WebControls.TextBox txtteunset8;
		protected global::System.Web.UI.WebControls.TextBox txtteunset9;
		protected global::System.Web.UI.WebControls.TextBox txtteunset10;
		protected global::System.Web.UI.WebControls.TextBox txtteunset11;
		protected global::System.Web.UI.WebControls.TextBox txtteunset12;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
