//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.enterprise {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcounty;
	protected global::System.Web.UI.WebControls.Label lblcommunty;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lbladdress;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_community;
	protected global::System.Web.UI.WebControls.Label lbltype;
	protected global::System.Web.UI.WebControls.Label lblmain_product;
	protected global::System.Web.UI.WebControls.Label lblarea;
	protected global::System.Web.UI.WebControls.Label lblstuff_amount;
	protected global::System.Web.UI.WebControls.Label lblimmigrant_stuff_amount;
	protected global::System.Web.UI.WebControls.Label lbllf_average_salary;
	protected global::System.Web.UI.WebControls.Label lblnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblteunset1;
	protected global::System.Web.UI.WebControls.Label lblteunset2;
	protected global::System.Web.UI.WebControls.Label lblteunset3;
	protected global::System.Web.UI.WebControls.Label lblteunset4;
	protected global::System.Web.UI.WebControls.Label lblteunset5;
	protected global::System.Web.UI.WebControls.Label lblteunset6;
	protected global::System.Web.UI.WebControls.Label lblteunset7;
	protected global::System.Web.UI.WebControls.Label lblteunset8;
	protected global::System.Web.UI.WebControls.Label lblteunset9;
	protected global::System.Web.UI.WebControls.Label lblteunset10;
	protected global::System.Web.UI.WebControls.Label lblteunset11;
	protected global::System.Web.UI.WebControls.Label lblteunset12;


       
    }
}
