//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.road {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity;
		protected global::System.Web.UI.WebControls.TextBox txtroad_class;
		protected global::System.Web.UI.WebControls.TextBox txtwidth;
		protected global::System.Web.UI.WebControls.TextBox txtpavement_width;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_length;
		protected global::System.Web.UI.WebControls.TextBox txtstructure;
		protected global::System.Web.UI.WebControls.TextBox txtis_dead_end_road;
		protected global::System.Web.UI.WebControls.TextBox txtdamage_road_length;
		protected global::System.Web.UI.WebControls.TextBox txtlarge_slope_road_length;
		protected global::System.Web.UI.WebControls.TextBox txtno_hard_road_length;
		protected global::System.Web.UI.WebControls.TextBox txtlack_width_road_length;
		protected global::System.Web.UI.WebControls.TextBox txtis_somewhere_no_link;
		protected global::System.Web.UI.WebControls.TextBox txtno_afforest_road_length;
		protected global::System.Web.UI.WebControls.TextBox txtless_afforest_road_length;
		protected global::System.Web.UI.WebControls.TextBox txtstreet_light_amount;
		protected global::System.Web.UI.WebControls.TextBox txtgood_street_light_amount;
		protected global::System.Web.UI.WebControls.TextBox txtroad_hydrant_amount;
		protected global::System.Web.UI.WebControls.TextBox txtgood_road_hydrant_amount;
		protected global::System.Web.UI.WebControls.TextBox txtroad_dustbin_amount;
		protected global::System.Web.UI.WebControls.TextBox txtgood_road_dustbin_amount;
		protected global::System.Web.UI.WebControls.TextBox txtroad_parking_space_num;
		protected global::System.Web.UI.WebControls.TextBox txtparking_space_use_rate;
		protected global::System.Web.UI.WebControls.TextBox txtnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txttrunset1;
		protected global::System.Web.UI.WebControls.TextBox txttrunset2;
		protected global::System.Web.UI.WebControls.TextBox txttrunset3;
		protected global::System.Web.UI.WebControls.TextBox txttrunset4;
		protected global::System.Web.UI.WebControls.TextBox txttrunset5;
		protected global::System.Web.UI.WebControls.TextBox txttrunset6;
		protected global::System.Web.UI.WebControls.TextBox txttrunset7;
		protected global::System.Web.UI.WebControls.TextBox txttrunset8;
		protected global::System.Web.UI.WebControls.TextBox txttrunset9;
		protected global::System.Web.UI.WebControls.TextBox txttrunset10;
		protected global::System.Web.UI.WebControls.TextBox txttrunset11;
		protected global::System.Web.UI.WebControls.TextBox txttrunset12;
		protected global::System.Web.UI.WebControls.TextBox txttrunset13;
		protected global::System.Web.UI.WebControls.TextBox txttrunset14;
		protected global::System.Web.UI.WebControls.TextBox txttrunset15;
		protected global::System.Web.UI.WebControls.TextBox txttrunset16;
		protected global::System.Web.UI.WebControls.TextBox txttrunset17;
		protected global::System.Web.UI.WebControls.TextBox txttrunset18;
		protected global::System.Web.UI.WebControls.TextBox txttrunset19;
		protected global::System.Web.UI.WebControls.TextBox txttrunset20;
		protected global::System.Web.UI.WebControls.TextBox txttrunset21;
		protected global::System.Web.UI.WebControls.TextBox txttrunset22;
		protected global::System.Web.UI.WebControls.TextBox txttrunset23;
		protected global::System.Web.UI.WebControls.TextBox txttrunset24;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
