//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.road {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblcommunity;
	protected global::System.Web.UI.WebControls.Label lblroad_class;
	protected global::System.Web.UI.WebControls.Label lblwidth;
	protected global::System.Web.UI.WebControls.Label lblpavement_width;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_length;
	protected global::System.Web.UI.WebControls.Label lblstructure;
	protected global::System.Web.UI.WebControls.Label lblis_dead_end_road;
	protected global::System.Web.UI.WebControls.Label lbldamage_road_length;
	protected global::System.Web.UI.WebControls.Label lbllarge_slope_road_length;
	protected global::System.Web.UI.WebControls.Label lblno_hard_road_length;
	protected global::System.Web.UI.WebControls.Label lbllack_width_road_length;
	protected global::System.Web.UI.WebControls.Label lblis_somewhere_no_link;
	protected global::System.Web.UI.WebControls.Label lblno_afforest_road_length;
	protected global::System.Web.UI.WebControls.Label lblless_afforest_road_length;
	protected global::System.Web.UI.WebControls.Label lblstreet_light_amount;
	protected global::System.Web.UI.WebControls.Label lblgood_street_light_amount;
	protected global::System.Web.UI.WebControls.Label lblroad_hydrant_amount;
	protected global::System.Web.UI.WebControls.Label lblgood_road_hydrant_amount;
	protected global::System.Web.UI.WebControls.Label lblroad_dustbin_amount;
	protected global::System.Web.UI.WebControls.Label lblgood_road_dustbin_amount;
	protected global::System.Web.UI.WebControls.Label lblroad_parking_space_num;
	protected global::System.Web.UI.WebControls.Label lblparking_space_use_rate;
	protected global::System.Web.UI.WebControls.Label lblnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lbltrunset1;
	protected global::System.Web.UI.WebControls.Label lbltrunset2;
	protected global::System.Web.UI.WebControls.Label lbltrunset3;
	protected global::System.Web.UI.WebControls.Label lbltrunset4;
	protected global::System.Web.UI.WebControls.Label lbltrunset5;
	protected global::System.Web.UI.WebControls.Label lbltrunset6;
	protected global::System.Web.UI.WebControls.Label lbltrunset7;
	protected global::System.Web.UI.WebControls.Label lbltrunset8;
	protected global::System.Web.UI.WebControls.Label lbltrunset9;
	protected global::System.Web.UI.WebControls.Label lbltrunset10;
	protected global::System.Web.UI.WebControls.Label lbltrunset11;
	protected global::System.Web.UI.WebControls.Label lbltrunset12;
	protected global::System.Web.UI.WebControls.Label lbltrunset13;
	protected global::System.Web.UI.WebControls.Label lbltrunset14;
	protected global::System.Web.UI.WebControls.Label lbltrunset15;
	protected global::System.Web.UI.WebControls.Label lbltrunset16;
	protected global::System.Web.UI.WebControls.Label lbltrunset17;
	protected global::System.Web.UI.WebControls.Label lbltrunset18;
	protected global::System.Web.UI.WebControls.Label lbltrunset19;
	protected global::System.Web.UI.WebControls.Label lbltrunset20;
	protected global::System.Web.UI.WebControls.Label lbltrunset21;
	protected global::System.Web.UI.WebControls.Label lbltrunset22;
	protected global::System.Web.UI.WebControls.Label lbltrunset23;
	protected global::System.Web.UI.WebControls.Label lbltrunset24;


       
    }
}
