//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_letter_view {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_county_government_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_county_government_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_county_industry_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_county_industry_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_street_agency_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_street_agency_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_neighborhood_committee_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_neighborhood_committee_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_immigration_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_basic_fac_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_service_fac_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_livelihood_difficulty_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lv_disputes_complaints_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset1;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset2;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset3;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset4;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset5;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset6;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset7;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset8;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset9;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset10;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset11;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset12;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset13;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset14;
		protected global::System.Web.UI.WebControls.TextBox txttclvunset15;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
