//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_letter_view {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_county_government_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_county_government_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_county_industry_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_county_industry_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_street_agency_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_street_agency_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_neighborhood_committee_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_neighborhood_committee_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_immigration_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_basic_fac_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_service_fac_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_livelihood_difficulty_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lv_disputes_complaints_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltclvunset1;
	protected global::System.Web.UI.WebControls.Label lbltclvunset2;
	protected global::System.Web.UI.WebControls.Label lbltclvunset3;
	protected global::System.Web.UI.WebControls.Label lbltclvunset4;
	protected global::System.Web.UI.WebControls.Label lbltclvunset5;
	protected global::System.Web.UI.WebControls.Label lbltclvunset6;
	protected global::System.Web.UI.WebControls.Label lbltclvunset7;
	protected global::System.Web.UI.WebControls.Label lbltclvunset8;
	protected global::System.Web.UI.WebControls.Label lbltclvunset9;
	protected global::System.Web.UI.WebControls.Label lbltclvunset10;
	protected global::System.Web.UI.WebControls.Label lbltclvunset11;
	protected global::System.Web.UI.WebControls.Label lbltclvunset12;
	protected global::System.Web.UI.WebControls.Label lbltclvunset13;
	protected global::System.Web.UI.WebControls.Label lbltclvunset14;
	protected global::System.Web.UI.WebControls.Label lbltclvunset15;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
