//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_immigrant {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtimmigrant_total_family_num;
		protected global::System.Web.UI.WebControls.TextBox txtimmigrant_total_population;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pure_resident_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_depart_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_enp_staves;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_enp_laidoff_staves;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_have_land_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_rural_to_town_pop;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcimunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcimunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcimunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcimunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcimunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcimunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcimunset7;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
