//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_immigrant {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblimmigrant_total_family_num;
	protected global::System.Web.UI.WebControls.Label lblimmigrant_total_population;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pure_resident_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_depart_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_enp_staves;
	protected global::System.Web.UI.WebControls.Label lblcommunity_enp_laidoff_staves;
	protected global::System.Web.UI.WebControls.Label lblcommunity_have_land_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_rural_to_town_pop;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcimunset1;
	protected global::System.Web.UI.WebControls.Label lbltcimunset2;
	protected global::System.Web.UI.WebControls.Label lbltcimunset3;
	protected global::System.Web.UI.WebControls.Label lbltcimunset4;
	protected global::System.Web.UI.WebControls.Label lbltcimunset5;
	protected global::System.Web.UI.WebControls.Label lbltcimunset6;
	protected global::System.Web.UI.WebControls.Label lbltcimunset7;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
