//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_road_problem {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fill_type;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_not_hardening_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_large_slope_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_insuf_width_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_pavement_damage_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_sidewalk_cb_damage_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_broken_road_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_sarea_lack_lroad;
	protected global::System.Web.UI.WebControls.Label lblcommunity_to_city_pasway_pavement_damage;
	protected global::System.Web.UI.WebControls.Label lblcommunity_to_city_pasway_pavement_insuf_width;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lack_motorway;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbltciunset11;
	protected global::System.Web.UI.WebControls.Label lbltciunset12;
	protected global::System.Web.UI.WebControls.Label lbltciunset13;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
