//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_population {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_total_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_reg_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_perm_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_man_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_female_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_younger_6_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_bet_7_and_15_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_bet_16_and_29_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_bet_30_and_39_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_bet_40_and_49_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_older_50_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_illiteracy_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prim_school_edu_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_junior_high_school_edu_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_senior_high_school_edu_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_junior_college_edu_pop;
		protected global::System.Web.UI.WebControls.TextBox txtaverage_education_time;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset13;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset14;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset15;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset16;
		protected global::System.Web.UI.WebControls.TextBox txttcpunset17;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_family_num;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
