//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_population {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_total_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_reg_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_perm_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_man_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_female_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_younger_6_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_bet_7_and_15_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_bet_16_and_29_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_bet_30_and_39_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_bet_40_and_49_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_older_50_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_illiteracy_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prim_school_edu_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_junior_high_school_edu_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_senior_high_school_edu_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_junior_college_edu_pop;
	protected global::System.Web.UI.WebControls.Label lblaverage_education_time;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcpunset1;
	protected global::System.Web.UI.WebControls.Label lbltcpunset2;
	protected global::System.Web.UI.WebControls.Label lbltcpunset3;
	protected global::System.Web.UI.WebControls.Label lbltcpunset4;
	protected global::System.Web.UI.WebControls.Label lbltcpunset5;
	protected global::System.Web.UI.WebControls.Label lbltcpunset6;
	protected global::System.Web.UI.WebControls.Label lbltcpunset7;
	protected global::System.Web.UI.WebControls.Label lbltcpunset8;
	protected global::System.Web.UI.WebControls.Label lbltcpunset10;
	protected global::System.Web.UI.WebControls.Label lbltcpunset11;
	protected global::System.Web.UI.WebControls.Label lbltcpunset12;
	protected global::System.Web.UI.WebControls.Label lbltcpunset13;
	protected global::System.Web.UI.WebControls.Label lbltcpunset14;
	protected global::System.Web.UI.WebControls.Label lbltcpunset15;
	protected global::System.Web.UI.WebControls.Label lbltcpunset16;
	protected global::System.Web.UI.WebControls.Label lbltcpunset17;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcommunity_family_num;


       
    }
}
