//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.kindergarten {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblcommunity;
		protected global::System.Web.UI.WebControls.TextBox txttype;
		protected global::System.Web.UI.WebControls.TextBox txtfloor_space;
		protected global::System.Web.UI.WebControls.TextBox txtgross_floor_area;
		protected global::System.Web.UI.WebControls.TextBox txtstudents_amount;
		protected global::System.Web.UI.WebControls.TextBox txtteachers_amount;
		protected global::System.Web.UI.WebControls.TextBox txtclass_amount;
		protected global::System.Web.UI.WebControls.TextBox txtteachers_students_rate;
		protected global::System.Web.UI.WebControls.TextBox txtactivity_room_area;
		protected global::System.Web.UI.WebControls.TextBox txtactivity_room_area_if_suff;
		protected global::System.Web.UI.WebControls.TextBox txtotds_activity_room_area;
		protected global::System.Web.UI.WebControls.TextBox txtotds_activity_room_area_if_suff;
		protected global::System.Web.UI.WebControls.TextBox txtafforest_area;
		protected global::System.Web.UI.WebControls.TextBox txtafforest_area_if_suff;
		protected global::System.Web.UI.WebControls.TextBox txtschool_bus_amount;
		protected global::System.Web.UI.WebControls.TextBox txtpick_up_students_amount_daily;
		protected global::System.Web.UI.WebControls.TextBox txtnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txttkunset1;
		protected global::System.Web.UI.WebControls.TextBox txttkunset2;
		protected global::System.Web.UI.WebControls.TextBox txttkunset3;
		protected global::System.Web.UI.WebControls.TextBox txttkunset4;
		protected global::System.Web.UI.WebControls.TextBox txttkunset5;
		protected global::System.Web.UI.WebControls.TextBox txttkunset6;
		protected global::System.Web.UI.WebControls.TextBox txttkunset7;
		protected global::System.Web.UI.WebControls.TextBox txttkunset8;
		protected global::System.Web.UI.WebControls.TextBox txttkunset9;
		protected global::System.Web.UI.WebControls.TextBox txttkunset10;
		protected global::System.Web.UI.WebControls.TextBox txttkunset11;
		protected global::System.Web.UI.WebControls.TextBox txttkunset12;
		protected global::System.Web.UI.WebControls.TextBox txttkunset13;
		protected global::System.Web.UI.WebControls.TextBox txttkunset14;
		protected global::System.Web.UI.WebControls.TextBox txttkunset15;
		protected global::System.Web.UI.WebControls.TextBox txttkunset16;
		protected global::System.Web.UI.WebControls.TextBox txttkunset17;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
