//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.kindergarten {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblcommunity;
	protected global::System.Web.UI.WebControls.Label lbltype;
	protected global::System.Web.UI.WebControls.Label lblfloor_space;
	protected global::System.Web.UI.WebControls.Label lblgross_floor_area;
	protected global::System.Web.UI.WebControls.Label lblstudents_amount;
	protected global::System.Web.UI.WebControls.Label lblteachers_amount;
	protected global::System.Web.UI.WebControls.Label lblclass_amount;
	protected global::System.Web.UI.WebControls.Label lblteachers_students_rate;
	protected global::System.Web.UI.WebControls.Label lblactivity_room_area;
	protected global::System.Web.UI.WebControls.Label lblactivity_room_area_if_suff;
	protected global::System.Web.UI.WebControls.Label lblotds_activity_room_area;
	protected global::System.Web.UI.WebControls.Label lblotds_activity_room_area_if_suff;
	protected global::System.Web.UI.WebControls.Label lblafforest_area;
	protected global::System.Web.UI.WebControls.Label lblafforest_area_if_suff;
	protected global::System.Web.UI.WebControls.Label lblschool_bus_amount;
	protected global::System.Web.UI.WebControls.Label lblpick_up_students_amount_daily;
	protected global::System.Web.UI.WebControls.Label lblnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbltkunset1;
	protected global::System.Web.UI.WebControls.Label lbltkunset2;
	protected global::System.Web.UI.WebControls.Label lbltkunset3;
	protected global::System.Web.UI.WebControls.Label lbltkunset4;
	protected global::System.Web.UI.WebControls.Label lbltkunset5;
	protected global::System.Web.UI.WebControls.Label lbltkunset6;
	protected global::System.Web.UI.WebControls.Label lbltkunset7;
	protected global::System.Web.UI.WebControls.Label lbltkunset8;
	protected global::System.Web.UI.WebControls.Label lbltkunset9;
	protected global::System.Web.UI.WebControls.Label lbltkunset10;
	protected global::System.Web.UI.WebControls.Label lbltkunset11;
	protected global::System.Web.UI.WebControls.Label lbltkunset12;
	protected global::System.Web.UI.WebControls.Label lbltkunset13;
	protected global::System.Web.UI.WebControls.Label lbltkunset14;
	protected global::System.Web.UI.WebControls.Label lbltkunset15;
	protected global::System.Web.UI.WebControls.Label lbltkunset16;
	protected global::System.Web.UI.WebControls.Label lbltkunset17;


       
    }
}
