//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_natural_gas {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_gas_regulating_station_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_natural_gas_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtlow_pressure_natural_gas_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtmiddle_pressuse_natural_gas_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtintermediate_pressure_natural_gas_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcngunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcngunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcngunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcngunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcngunset5;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
