//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_natural_gas {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_gas_regulating_station_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_natural_gas_pipe_length;
	protected global::System.Web.UI.WebControls.Label lbllow_pressure_natural_gas_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblmiddle_pressuse_natural_gas_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblintermediate_pressure_natural_gas_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcngunset1;
	protected global::System.Web.UI.WebControls.Label lbltcngunset2;
	protected global::System.Web.UI.WebControls.Label lbltcngunset3;
	protected global::System.Web.UI.WebControls.Label lbltcngunset4;
	protected global::System.Web.UI.WebControls.Label lbltcngunset5;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
