//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.excel_span_structure {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtproperty;
		protected global::System.Web.UI.WebControls.TextBox txtexcel_name;
		protected global::System.Web.UI.WebControls.TextBox txttable_name;
		protected global::System.Web.UI.WebControls.TextBox txtrow_num;
		protected global::System.Web.UI.WebControls.TextBox txtcolumn_num;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
