//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.labor_force {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtcounty;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity;
		protected global::System.Web.UI.WebControls.TextBox txtlf_have_a_job_pop;
		protected global::System.Web.UI.WebControls.TextBox txtlf_have_a_steady_job_pop;
		protected global::System.Web.UI.WebControls.TextBox txtempm_information_platform_num;
		protected global::System.Web.UI.WebControls.TextBox txtempm_information_platform_information_num;
		protected global::System.Web.UI.WebControls.TextBox txtpublic_spirited_job_pop;
		protected global::System.Web.UI.WebControls.TextBox txtclean_keeping_pop;
		protected global::System.Web.UI.WebControls.TextBox txtsecurity_guard_pop;
		protected global::System.Web.UI.WebControls.TextBox txtfarm_produce_fair_administrator_pop;
		protected global::System.Web.UI.WebControls.TextBox txtother_job_pop;
		protected global::System.Web.UI.WebControls.TextBox txtenp_supportive_num;
		protected global::System.Web.UI.WebControls.TextBox txtsmall_manual_processing_enp_num;
		protected global::System.Web.UI.WebControls.TextBox txtfood_enp_num;
		protected global::System.Web.UI.WebControls.TextBox txtsewing_embroidery_enp_num;
		protected global::System.Web.UI.WebControls.TextBox txtother_enp_supportive_num;
		protected global::System.Web.UI.WebControls.TextBox txtnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset1;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset2;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset3;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset4;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset5;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset6;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset7;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset8;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset9;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset10;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset11;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset12;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset13;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset14;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset15;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset16;
		protected global::System.Web.UI.WebControls.TextBox txttlfunset17;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
