//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.labor_force {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcounty;
	protected global::System.Web.UI.WebControls.Label lblcommunity;
	protected global::System.Web.UI.WebControls.Label lbllf_have_a_job_pop;
	protected global::System.Web.UI.WebControls.Label lbllf_have_a_steady_job_pop;
	protected global::System.Web.UI.WebControls.Label lblempm_information_platform_num;
	protected global::System.Web.UI.WebControls.Label lblempm_information_platform_information_num;
	protected global::System.Web.UI.WebControls.Label lblpublic_spirited_job_pop;
	protected global::System.Web.UI.WebControls.Label lblclean_keeping_pop;
	protected global::System.Web.UI.WebControls.Label lblsecurity_guard_pop;
	protected global::System.Web.UI.WebControls.Label lblfarm_produce_fair_administrator_pop;
	protected global::System.Web.UI.WebControls.Label lblother_job_pop;
	protected global::System.Web.UI.WebControls.Label lblenp_supportive_num;
	protected global::System.Web.UI.WebControls.Label lblsmall_manual_processing_enp_num;
	protected global::System.Web.UI.WebControls.Label lblfood_enp_num;
	protected global::System.Web.UI.WebControls.Label lblsewing_embroidery_enp_num;
	protected global::System.Web.UI.WebControls.Label lblother_enp_supportive_num;
	protected global::System.Web.UI.WebControls.Label lblnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltlfunset1;
	protected global::System.Web.UI.WebControls.Label lbltlfunset2;
	protected global::System.Web.UI.WebControls.Label lbltlfunset3;
	protected global::System.Web.UI.WebControls.Label lbltlfunset4;
	protected global::System.Web.UI.WebControls.Label lbltlfunset5;
	protected global::System.Web.UI.WebControls.Label lbltlfunset6;
	protected global::System.Web.UI.WebControls.Label lbltlfunset7;
	protected global::System.Web.UI.WebControls.Label lbltlfunset8;
	protected global::System.Web.UI.WebControls.Label lbltlfunset9;
	protected global::System.Web.UI.WebControls.Label lbltlfunset10;
	protected global::System.Web.UI.WebControls.Label lbltlfunset11;
	protected global::System.Web.UI.WebControls.Label lbltlfunset12;
	protected global::System.Web.UI.WebControls.Label lbltlfunset13;
	protected global::System.Web.UI.WebControls.Label lbltlfunset14;
	protected global::System.Web.UI.WebControls.Label lbltlfunset15;
	protected global::System.Web.UI.WebControls.Label lbltlfunset16;
	protected global::System.Web.UI.WebControls.Label lbltlfunset17;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
