//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_sanitation_problem {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fill_type;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_lack_rd_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_lack_rd_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_insuf_resd_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_along_rs_garbage_pup_num;
	protected global::System.Web.UI.WebControls.Label lblcommuniyt_along_rs_garbage_stack_amount;
	protected global::System.Web.UI.WebControls.Label lblcommunity_bsa_etc_hc_garbage_pup_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_bsa_etc_hc_garbage_stack_amount;
	protected global::System.Web.UI.WebControls.Label lblcommunity_toilet_insuf_pt_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_regional_insuf_sf_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbltciunset11;
	protected global::System.Web.UI.WebControls.Label lbltciunset12;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
