//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_parking_lot {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_parking_space_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_parking_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_parking_space_use_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_parking_lot_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_grand_parking_lot_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_underg_parking_lot_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_overg_parking_lot_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_parking_lot_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_parking_space_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_parking_lot_area_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdis_150m_public_parking_lot_num;
		protected global::System.Web.UI.WebControls.TextBox txtdis_150m_public_parking_lot_area;
		protected global::System.Web.UI.WebControls.TextBox txtdis_150m_public_parking_space_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcplunset13;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
