//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_parking_lot {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_parking_space_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_parking_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_parking_space_use_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_parking_lot_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_grand_parking_lot_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_underg_parking_lot_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_overg_parking_lot_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_parking_lot_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_parking_space_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_parking_lot_area_rate;
	protected global::System.Web.UI.WebControls.Label lbldis_150m_public_parking_lot_num;
	protected global::System.Web.UI.WebControls.Label lbldis_150m_public_parking_lot_area;
	protected global::System.Web.UI.WebControls.Label lbldis_150m_public_parking_space_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcplunset1;
	protected global::System.Web.UI.WebControls.Label lbltcplunset2;
	protected global::System.Web.UI.WebControls.Label lbltcplunset3;
	protected global::System.Web.UI.WebControls.Label lbltcplunset4;
	protected global::System.Web.UI.WebControls.Label lbltcplunset5;
	protected global::System.Web.UI.WebControls.Label lbltcplunset6;
	protected global::System.Web.UI.WebControls.Label lbltcplunset7;
	protected global::System.Web.UI.WebControls.Label lbltcplunset8;
	protected global::System.Web.UI.WebControls.Label lbltcplunset9;
	protected global::System.Web.UI.WebControls.Label lbltcplunset10;
	protected global::System.Web.UI.WebControls.Label lbltcplunset11;
	protected global::System.Web.UI.WebControls.Label lbltcplunset12;
	protected global::System.Web.UI.WebControls.Label lbltcplunset13;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
