//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_road_problem_finished {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_hardening_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_maintain_reform_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_maintain_reform_len;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_maintain_reform_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pavement_colorful_brick_len;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pavement_colorful_brick_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_road_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_road_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_maintain_reform_num_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_maintain_reform_len_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_maintain_reform_area_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_vehicles_road_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_vehicles_road_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_white_change_black_road_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_white_change_black_road_area;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txttciunset10;
		protected global::System.Web.UI.WebControls.TextBox txttciunset11;
		protected global::System.Web.UI.WebControls.TextBox txttciunset12;
		protected global::System.Web.UI.WebControls.TextBox txttciunset13;
		protected global::System.Web.UI.WebControls.TextBox txttciunset14;
		protected global::System.Web.UI.WebControls.TextBox txttciunset15;
		protected global::System.Web.UI.WebControls.TextBox txttciunset16;
		protected global::System.Web.UI.WebControls.TextBox txttciunset17;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_road_num_for_update;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_added_road_area_for_update;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
