//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_road_problem_finished {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_hardening_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_maintain_reform_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_maintain_reform_len;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_maintain_reform_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pavement_colorful_brick_len;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pavement_colorful_brick_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_road_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_road_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_maintain_reform_num_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_maintain_reform_len_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_maintain_reform_area_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_vehicles_road_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_vehicles_road_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_white_change_black_road_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_white_change_black_road_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbltciunset11;
	protected global::System.Web.UI.WebControls.Label lbltciunset12;
	protected global::System.Web.UI.WebControls.Label lbltciunset13;
	protected global::System.Web.UI.WebControls.Label lbltciunset14;
	protected global::System.Web.UI.WebControls.Label lbltciunset15;
	protected global::System.Web.UI.WebControls.Label lbltciunset16;
	protected global::System.Web.UI.WebControls.Label lbltciunset17;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_road_num_for_update;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_road_area_for_update;


       
    }
}
