//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.concil_house {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtid;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity;
		protected global::System.Web.UI.WebControls.TextBox txtbuilding;
		protected global::System.Web.UI.WebControls.TextBox txtunit;
		protected global::System.Web.UI.WebControls.TextBox txtstructure;
		protected global::System.Web.UI.WebControls.TextBox txtfloor;
		protected global::System.Web.UI.WebControls.TextBox txthouse;
		protected global::System.Web.UI.WebControls.TextBox txtfinish_time;
		protected global::System.Web.UI.WebControls.TextBox txtgross_floor_area;
		protected global::System.Web.UI.WebControls.TextBox txttiled_wall_area;
		protected global::System.Web.UI.WebControls.TextBox txtfamily_num;
		protected global::System.Web.UI.WebControls.TextBox txtpop_num;
		protected global::System.Web.UI.WebControls.TextBox txtslight_deform_cra_area;
		protected global::System.Web.UI.WebControls.TextBox txtbase_subs_area;
		protected global::System.Web.UI.WebControls.TextBox txtdila_buil_area;
		protected global::System.Web.UI.WebControls.TextBox txtstru_safety_prob_fam_num;
		protected global::System.Web.UI.WebControls.TextBox txtslight_deform_cra_pop;
		protected global::System.Web.UI.WebControls.TextBox txtseepage_buil_area;
		protected global::System.Web.UI.WebControls.TextBox txtseepage_fam_num;
		protected global::System.Web.UI.WebControls.TextBox txtseepage_pop;
		protected global::System.Web.UI.WebControls.TextBox txttile_paint_cra_holl_buil_area;
		protected global::System.Web.UI.WebControls.TextBox txtnote_information;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttchunset1;
		protected global::System.Web.UI.WebControls.TextBox txttchunset2;
		protected global::System.Web.UI.WebControls.TextBox txttchunset3;
		protected global::System.Web.UI.WebControls.TextBox txttchunset4;
		protected global::System.Web.UI.WebControls.TextBox txttchunset5;
		protected global::System.Web.UI.WebControls.TextBox txttchunset6;
		protected global::System.Web.UI.WebControls.TextBox txttchunset7;
		protected global::System.Web.UI.WebControls.TextBox txttchunset8;
		protected global::System.Web.UI.WebControls.TextBox txttchunset9;
		protected global::System.Web.UI.WebControls.TextBox txttchunset10;
		protected global::System.Web.UI.WebControls.TextBox txttchunset11;
		protected global::System.Web.UI.WebControls.TextBox txttchunset12;
		protected global::System.Web.UI.WebControls.TextBox txttchunset13;
		protected global::System.Web.UI.WebControls.TextBox txttchunset14;
		protected global::System.Web.UI.WebControls.TextBox txttchunset15;
		protected global::System.Web.UI.WebControls.TextBox txttchunset16;
		protected global::System.Web.UI.WebControls.TextBox txttchunset17;
		protected global::System.Web.UI.WebControls.TextBox txttchunset18;
		protected global::System.Web.UI.WebControls.TextBox txttchunset19;
		protected global::System.Web.UI.WebControls.TextBox txttchunset20;
		protected global::System.Web.UI.WebControls.TextBox txttchunset21;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
