//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.concil_house {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcommunity;
	protected global::System.Web.UI.WebControls.Label lblbuilding;
	protected global::System.Web.UI.WebControls.Label lblunit;
	protected global::System.Web.UI.WebControls.Label lblstructure;
	protected global::System.Web.UI.WebControls.Label lblfloor;
	protected global::System.Web.UI.WebControls.Label lblhouse;
	protected global::System.Web.UI.WebControls.Label lblfinish_time;
	protected global::System.Web.UI.WebControls.Label lblgross_floor_area;
	protected global::System.Web.UI.WebControls.Label lbltiled_wall_area;
	protected global::System.Web.UI.WebControls.Label lblfamily_num;
	protected global::System.Web.UI.WebControls.Label lblpop_num;
	protected global::System.Web.UI.WebControls.Label lblslight_deform_cra_area;
	protected global::System.Web.UI.WebControls.Label lblbase_subs_area;
	protected global::System.Web.UI.WebControls.Label lbldila_buil_area;
	protected global::System.Web.UI.WebControls.Label lblstru_safety_prob_fam_num;
	protected global::System.Web.UI.WebControls.Label lblslight_deform_cra_pop;
	protected global::System.Web.UI.WebControls.Label lblseepage_buil_area;
	protected global::System.Web.UI.WebControls.Label lblseepage_fam_num;
	protected global::System.Web.UI.WebControls.Label lblseepage_pop;
	protected global::System.Web.UI.WebControls.Label lbltile_paint_cra_holl_buil_area;
	protected global::System.Web.UI.WebControls.Label lblnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltchunset1;
	protected global::System.Web.UI.WebControls.Label lbltchunset2;
	protected global::System.Web.UI.WebControls.Label lbltchunset3;
	protected global::System.Web.UI.WebControls.Label lbltchunset4;
	protected global::System.Web.UI.WebControls.Label lbltchunset5;
	protected global::System.Web.UI.WebControls.Label lbltchunset6;
	protected global::System.Web.UI.WebControls.Label lbltchunset7;
	protected global::System.Web.UI.WebControls.Label lbltchunset8;
	protected global::System.Web.UI.WebControls.Label lbltchunset9;
	protected global::System.Web.UI.WebControls.Label lbltchunset10;
	protected global::System.Web.UI.WebControls.Label lbltchunset11;
	protected global::System.Web.UI.WebControls.Label lbltchunset12;
	protected global::System.Web.UI.WebControls.Label lbltchunset13;
	protected global::System.Web.UI.WebControls.Label lbltchunset14;
	protected global::System.Web.UI.WebControls.Label lbltchunset15;
	protected global::System.Web.UI.WebControls.Label lbltchunset16;
	protected global::System.Web.UI.WebControls.Label lbltchunset17;
	protected global::System.Web.UI.WebControls.Label lbltchunset18;
	protected global::System.Web.UI.WebControls.Label lbltchunset19;
	protected global::System.Web.UI.WebControls.Label lbltchunset20;
	protected global::System.Web.UI.WebControls.Label lbltchunset21;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
