//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_culture_sports {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_culture_sports_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_culture_sports_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_otd_cul_spo_fac_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_otd_cul_spo_fac_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_cul_squ_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_cul_squ_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_otd_entm_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_otd_entm_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_child_plg_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_child_plg_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ind_actv_spa_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ind_actv_spa_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ind_actv_spa_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_cul_sta_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_cul_sta_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_cul_sta_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_cul_room_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_cul_room_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_cul_room_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_fit_fac_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_fit_fac_intact_rate;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset1;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset2;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset3;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset4;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset5;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset6;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset7;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset8;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset9;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset10;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset11;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset12;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset13;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset14;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset15;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset16;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset17;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset18;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset19;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset20;
		protected global::System.Web.UI.WebControls.TextBox txttccsunset21;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
