//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_culture_sports {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_culture_sports_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_culture_sports_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_otd_cul_spo_fac_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_otd_cul_spo_fac_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_cul_squ_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_cul_squ_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_otd_entm_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_otd_entm_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_child_plg_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_child_plg_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ind_actv_spa_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ind_actv_spa_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ind_actv_spa_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_cul_sta_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_cul_sta_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_cul_sta_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_cul_room_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_cul_room_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_cul_room_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fit_fac_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fit_fac_intact_rate;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltccsunset1;
	protected global::System.Web.UI.WebControls.Label lbltccsunset2;
	protected global::System.Web.UI.WebControls.Label lbltccsunset3;
	protected global::System.Web.UI.WebControls.Label lbltccsunset4;
	protected global::System.Web.UI.WebControls.Label lbltccsunset5;
	protected global::System.Web.UI.WebControls.Label lbltccsunset6;
	protected global::System.Web.UI.WebControls.Label lbltccsunset7;
	protected global::System.Web.UI.WebControls.Label lbltccsunset8;
	protected global::System.Web.UI.WebControls.Label lbltccsunset9;
	protected global::System.Web.UI.WebControls.Label lbltccsunset10;
	protected global::System.Web.UI.WebControls.Label lbltccsunset11;
	protected global::System.Web.UI.WebControls.Label lbltccsunset12;
	protected global::System.Web.UI.WebControls.Label lbltccsunset13;
	protected global::System.Web.UI.WebControls.Label lbltccsunset14;
	protected global::System.Web.UI.WebControls.Label lbltccsunset15;
	protected global::System.Web.UI.WebControls.Label lbltccsunset16;
	protected global::System.Web.UI.WebControls.Label lbltccsunset17;
	protected global::System.Web.UI.WebControls.Label lbltccsunset18;
	protected global::System.Web.UI.WebControls.Label lbltccsunset19;
	protected global::System.Web.UI.WebControls.Label lbltccsunset20;
	protected global::System.Web.UI.WebControls.Label lbltccsunset21;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
