//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_elec_supply_problem {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fill_type;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_transformer_cap_ins_buil_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_transformer_cap_ins_hou_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_senescent_elec_wireways_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_senescent_elec_wireways_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_no_one_hou_one_meter_buil_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_no_one_hou_one_meter_hou_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unsafe_transformer_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_elec_net_insuf;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txttciunset10;
		protected global::System.Web.UI.WebControls.TextBox txttciunset11;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
