//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_traffic {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_passenger_station_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_station_waiting_room_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_station_parking_lot_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_bus_trips;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_quay_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_passenger_and_goods_quay_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_goods_quay_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_passenger_quay_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_docking_point;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_passenger_quay_waiting_room_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_passenger_quay_parking_lot_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_passenger_quay_ship_trips;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_passenger_quay_dis_to_county;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttctunset1;
		protected global::System.Web.UI.WebControls.TextBox txttctunset2;
		protected global::System.Web.UI.WebControls.TextBox txttctunset3;
		protected global::System.Web.UI.WebControls.TextBox txttctunset4;
		protected global::System.Web.UI.WebControls.TextBox txttctunset5;
		protected global::System.Web.UI.WebControls.TextBox txttctunset6;
		protected global::System.Web.UI.WebControls.TextBox txttctunset7;
		protected global::System.Web.UI.WebControls.TextBox txttctunset8;
		protected global::System.Web.UI.WebControls.TextBox txttctunset9;
		protected global::System.Web.UI.WebControls.TextBox txttctunset10;
		protected global::System.Web.UI.WebControls.TextBox txttctunset11;
		protected global::System.Web.UI.WebControls.TextBox txttctunset12;
		protected global::System.Web.UI.WebControls.TextBox txttctunset13;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
