//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_traffic {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_passenger_station_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_station_waiting_room_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_station_parking_lot_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_bus_trips;
	protected global::System.Web.UI.WebControls.Label lblcommunity_quay_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_passenger_and_goods_quay_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_goods_quay_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_passenger_quay_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_docking_point;
	protected global::System.Web.UI.WebControls.Label lblcommunity_passenger_quay_waiting_room_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_passenger_quay_parking_lot_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_passenger_quay_ship_trips;
	protected global::System.Web.UI.WebControls.Label lblcommunity_passenger_quay_dis_to_county;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltctunset1;
	protected global::System.Web.UI.WebControls.Label lbltctunset2;
	protected global::System.Web.UI.WebControls.Label lbltctunset3;
	protected global::System.Web.UI.WebControls.Label lbltctunset4;
	protected global::System.Web.UI.WebControls.Label lbltctunset5;
	protected global::System.Web.UI.WebControls.Label lbltctunset6;
	protected global::System.Web.UI.WebControls.Label lbltctunset7;
	protected global::System.Web.UI.WebControls.Label lbltctunset8;
	protected global::System.Web.UI.WebControls.Label lbltctunset9;
	protected global::System.Web.UI.WebControls.Label lbltctunset10;
	protected global::System.Web.UI.WebControls.Label lbltctunset11;
	protected global::System.Web.UI.WebControls.Label lbltctunset12;
	protected global::System.Web.UI.WebControls.Label lbltctunset13;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
