//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.Community_Indicator {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pop_total_density;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pop_pure_density;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_plot_ratio;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_struc_safe_problem_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_seepage_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_tile_paint_cra_holl_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_density;
		protected global::System.Web.UI.WebControls.TextBox txtroad_per_capita_availability;
		protected global::System.Web.UI.WebControls.TextBox txtno_hard_road_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdamage_road_rate;
		protected global::System.Web.UI.WebControls.TextBox txtlarge_slope_road_rate;
		protected global::System.Web.UI.WebControls.TextBox txtlack_width_road_rate;
		protected global::System.Web.UI.WebControls.TextBox txtneed_new_repair_road_rate;
		protected global::System.Web.UI.WebControls.TextBox txtneed_improve_link_ots_road;
		protected global::System.Web.UI.WebControls.TextBox txtno_brick_road_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdamage_brick_road_rate;
		protected global::System.Web.UI.WebControls.TextBox txttap_water_fam_rate;
		protected global::System.Web.UI.WebControls.TextBox txtno_water_meter_house_rate;
		protected global::System.Web.UI.WebControls.TextBox txtwater_supply_insuff_family_rate;
		protected global::System.Web.UI.WebControls.TextBox txtwater_pressure_insuff_family_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcaliber_samll_pipe_lenth_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdamage_pipe_lenth_rate;
		protected global::System.Web.UI.WebControls.TextBox txtsenescent_erosive_pipe_length_rate;
		protected global::System.Web.UI.WebControls.TextBox txtsewage_collection_rate;
		protected global::System.Web.UI.WebControls.TextBox txtsewage_handle_rate;
		protected global::System.Web.UI.WebControls.TextBox txtnot_reasonable_drain_pipe_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcaliber_samll_drain_pipe_rate;
		protected global::System.Web.UI.WebControls.TextBox txtseptic_tank_capacity_small_rate;
		protected global::System.Web.UI.WebControls.TextBox txtsenescent_erosive_drain_pipe_length_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdamage_drain_pipe_rate;
		protected global::System.Web.UI.WebControls.TextBox txtbroken_leaking_septic_tank_rate;
		protected global::System.Web.UI.WebControls.TextBox txtno_link_drain_pipe_net_famliy_rate;
		protected global::System.Web.UI.WebControls.TextBox txtelec_reliable_rate;
		protected global::System.Web.UI.WebControls.TextBox txtelec_capacity_lack_family_rate;
		protected global::System.Web.UI.WebControls.TextBox txtsenescent_elec_wireways_rate;
		protected global::System.Web.UI.WebControls.TextBox txtno_elec_meter_house_rate;
		protected global::System.Web.UI.WebControls.TextBox txtnot_norm_transformer_rate;
		protected global::System.Web.UI.WebControls.TextBox txtno_light_road_length_rate;
		protected global::System.Web.UI.WebControls.TextBox txtlack_light_road_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdamage_road_light_rate;
		protected global::System.Web.UI.WebControls.TextBox txtpassway_light_wireway_damage_house_rate;
		protected global::System.Web.UI.WebControls.TextBox txtpassway_light_wireway_damage_family_rate;
		protected global::System.Web.UI.WebControls.TextBox txtgreenland_rate;
		protected global::System.Web.UI.WebControls.TextBox txtgreenland_per_capita_area;
		protected global::System.Web.UI.WebControls.TextBox txtno_lack_afforest_road_length_rate;
		protected global::System.Web.UI.WebControls.TextBox txtno_lack_afforest_house_rate;
		protected global::System.Web.UI.WebControls.TextBox txtlack_otds_hydrant_road_length_rate;
		protected global::System.Web.UI.WebControls.TextBox txtlack_inds_hydrant_house_rate;
		protected global::System.Web.UI.WebControls.TextBox txtextinguisher_insuff_building_rate;
		protected global::System.Web.UI.WebControls.TextBox txtff_pipe_damage_length_rate;
		protected global::System.Web.UI.WebControls.TextBox txtff_road_block_building_rate;
		protected global::System.Web.UI.WebControls.TextBox txtrubbish_collection_rate;
		protected global::System.Web.UI.WebControls.TextBox txtrubbish_handle_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdustbin_lack_road_length_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdustbin_lack_house_rate;
		protected global::System.Web.UI.WebControls.TextBox txtlong_term_rubbish_stack_rate;
		protected global::System.Web.UI.WebControls.TextBox txteducation_fs_indicator;
		protected global::System.Web.UI.WebControls.TextBox txteducation_gfa_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtmedical_fs_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtmedical_gfa_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtculture_sports_fs_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtculture_sports_gfa_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_service_fs_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_service_gfa_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtcommerce_fs_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtcommerce_gfa_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtfarm_produce_fair_fs_indicator;
		protected global::System.Web.UI.WebControls.TextBox txtfarm_produce_fair_gfa_indicator;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txttciunset10;
		protected global::System.Web.UI.WebControls.TextBox txttciunset11;
		protected global::System.Web.UI.WebControls.TextBox txttciunset12;
		protected global::System.Web.UI.WebControls.TextBox txttciunset13;
		protected global::System.Web.UI.WebControls.TextBox txttciunset14;
		protected global::System.Web.UI.WebControls.TextBox txttciunset15;
		protected global::System.Web.UI.WebControls.TextBox txttciunset16;
		protected global::System.Web.UI.WebControls.TextBox txttciunset17;
		protected global::System.Web.UI.WebControls.TextBox txttciunset18;
		protected global::System.Web.UI.WebControls.TextBox txttciunset19;
		protected global::System.Web.UI.WebControls.TextBox txttciunset20;
		protected global::System.Web.UI.WebControls.TextBox txttciunset21;
		protected global::System.Web.UI.WebControls.TextBox txttciunset22;
		protected global::System.Web.UI.WebControls.TextBox txttciunset23;
		protected global::System.Web.UI.WebControls.TextBox txttciunset24;
		protected global::System.Web.UI.WebControls.TextBox txttciunset25;
		protected global::System.Web.UI.WebControls.TextBox txttciunset26;
		protected global::System.Web.UI.WebControls.TextBox txttciunset27;
		protected global::System.Web.UI.WebControls.TextBox txttciunset28;
		protected global::System.Web.UI.WebControls.TextBox txttciunset29;
		protected global::System.Web.UI.WebControls.TextBox txttciunset30;
		protected global::System.Web.UI.WebControls.TextBox txttciunset31;
		protected global::System.Web.UI.WebControls.TextBox txttciunset32;
		protected global::System.Web.UI.WebControls.TextBox txttciunset33;
		protected global::System.Web.UI.WebControls.TextBox txttciunset34;
		protected global::System.Web.UI.WebControls.TextBox txttciunset35;
		protected global::System.Web.UI.WebControls.TextBox txttciunset36;
		protected global::System.Web.UI.WebControls.TextBox txttciunset37;
		protected global::System.Web.UI.WebControls.TextBox txttciunset38;
		protected global::System.Web.UI.WebControls.TextBox txttciunset39;
		protected global::System.Web.UI.WebControls.TextBox txttciunset40;
		protected global::System.Web.UI.WebControls.TextBox txttciunset41;
		protected global::System.Web.UI.WebControls.TextBox txttciunset42;
		protected global::System.Web.UI.WebControls.TextBox txttciunset43;
		protected global::System.Web.UI.WebControls.TextBox txttciunset44;
		protected global::System.Web.UI.WebControls.TextBox txttciunset45;
		protected global::System.Web.UI.WebControls.TextBox txttciunset46;
		protected global::System.Web.UI.WebControls.TextBox txttciunset47;
		protected global::System.Web.UI.WebControls.TextBox txttciunset48;
		protected global::System.Web.UI.WebControls.TextBox txttciunset49;
		protected global::System.Web.UI.WebControls.TextBox txttciunset50;
		protected global::System.Web.UI.WebControls.TextBox txttciunset51;
		protected global::System.Web.UI.WebControls.TextBox txttciunset52;
		protected global::System.Web.UI.WebControls.TextBox txttciunset53;
		protected global::System.Web.UI.WebControls.TextBox txttciunset54;
		protected global::System.Web.UI.WebControls.TextBox txttciunset55;
		protected global::System.Web.UI.WebControls.TextBox txttciunset56;
		protected global::System.Web.UI.WebControls.TextBox txttciunset57;
		protected global::System.Web.UI.WebControls.TextBox txttciunset58;
		protected global::System.Web.UI.WebControls.TextBox txttciunset59;
		protected global::System.Web.UI.WebControls.TextBox txttciunset60;
		protected global::System.Web.UI.WebControls.TextBox txttciunset61;
		protected global::System.Web.UI.WebControls.TextBox txttciunset62;
		protected global::System.Web.UI.WebControls.TextBox txttciunset63;
		protected global::System.Web.UI.WebControls.TextBox txttciunset64;
		protected global::System.Web.UI.WebControls.TextBox txttciunset65;
		protected global::System.Web.UI.WebControls.TextBox txttciunset66;
		protected global::System.Web.UI.WebControls.TextBox txttciunset67;
		protected global::System.Web.UI.WebControls.TextBox txttciunset68;
		protected global::System.Web.UI.WebControls.TextBox txttciunset69;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txthouse_area_per_people;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_help_figure;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_develop_figure;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_engel_coefficient;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_gini_coefficient;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
