//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.Community_Indicator {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pop_total_density;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pop_pure_density;
	protected global::System.Web.UI.WebControls.Label lblcommunity_plot_ratio;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_struc_safe_problem_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_seepage_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_tile_paint_cra_holl_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_density;
	protected global::System.Web.UI.WebControls.Label lblroad_per_capita_availability;
	protected global::System.Web.UI.WebControls.Label lblno_hard_road_rate;
	protected global::System.Web.UI.WebControls.Label lbldamage_road_rate;
	protected global::System.Web.UI.WebControls.Label lbllarge_slope_road_rate;
	protected global::System.Web.UI.WebControls.Label lbllack_width_road_rate;
	protected global::System.Web.UI.WebControls.Label lblneed_new_repair_road_rate;
	protected global::System.Web.UI.WebControls.Label lblneed_improve_link_ots_road;
	protected global::System.Web.UI.WebControls.Label lblno_brick_road_rate;
	protected global::System.Web.UI.WebControls.Label lbldamage_brick_road_rate;
	protected global::System.Web.UI.WebControls.Label lbltap_water_fam_rate;
	protected global::System.Web.UI.WebControls.Label lblno_water_meter_house_rate;
	protected global::System.Web.UI.WebControls.Label lblwater_supply_insuff_family_rate;
	protected global::System.Web.UI.WebControls.Label lblwater_pressure_insuff_family_rate;
	protected global::System.Web.UI.WebControls.Label lblcaliber_samll_pipe_lenth_rate;
	protected global::System.Web.UI.WebControls.Label lbldamage_pipe_lenth_rate;
	protected global::System.Web.UI.WebControls.Label lblsenescent_erosive_pipe_length_rate;
	protected global::System.Web.UI.WebControls.Label lblsewage_collection_rate;
	protected global::System.Web.UI.WebControls.Label lblsewage_handle_rate;
	protected global::System.Web.UI.WebControls.Label lblnot_reasonable_drain_pipe_rate;
	protected global::System.Web.UI.WebControls.Label lblcaliber_samll_drain_pipe_rate;
	protected global::System.Web.UI.WebControls.Label lblseptic_tank_capacity_small_rate;
	protected global::System.Web.UI.WebControls.Label lblsenescent_erosive_drain_pipe_length_rate;
	protected global::System.Web.UI.WebControls.Label lbldamage_drain_pipe_rate;
	protected global::System.Web.UI.WebControls.Label lblbroken_leaking_septic_tank_rate;
	protected global::System.Web.UI.WebControls.Label lblno_link_drain_pipe_net_famliy_rate;
	protected global::System.Web.UI.WebControls.Label lblelec_reliable_rate;
	protected global::System.Web.UI.WebControls.Label lblelec_capacity_lack_family_rate;
	protected global::System.Web.UI.WebControls.Label lblsenescent_elec_wireways_rate;
	protected global::System.Web.UI.WebControls.Label lblno_elec_meter_house_rate;
	protected global::System.Web.UI.WebControls.Label lblnot_norm_transformer_rate;
	protected global::System.Web.UI.WebControls.Label lblno_light_road_length_rate;
	protected global::System.Web.UI.WebControls.Label lbllack_light_road_rate;
	protected global::System.Web.UI.WebControls.Label lbldamage_road_light_rate;
	protected global::System.Web.UI.WebControls.Label lblpassway_light_wireway_damage_house_rate;
	protected global::System.Web.UI.WebControls.Label lblpassway_light_wireway_damage_family_rate;
	protected global::System.Web.UI.WebControls.Label lblgreenland_rate;
	protected global::System.Web.UI.WebControls.Label lblgreenland_per_capita_area;
	protected global::System.Web.UI.WebControls.Label lblno_lack_afforest_road_length_rate;
	protected global::System.Web.UI.WebControls.Label lblno_lack_afforest_house_rate;
	protected global::System.Web.UI.WebControls.Label lbllack_otds_hydrant_road_length_rate;
	protected global::System.Web.UI.WebControls.Label lbllack_inds_hydrant_house_rate;
	protected global::System.Web.UI.WebControls.Label lblextinguisher_insuff_building_rate;
	protected global::System.Web.UI.WebControls.Label lblff_pipe_damage_length_rate;
	protected global::System.Web.UI.WebControls.Label lblff_road_block_building_rate;
	protected global::System.Web.UI.WebControls.Label lblrubbish_collection_rate;
	protected global::System.Web.UI.WebControls.Label lblrubbish_handle_rate;
	protected global::System.Web.UI.WebControls.Label lbldustbin_lack_road_length_rate;
	protected global::System.Web.UI.WebControls.Label lbldustbin_lack_house_rate;
	protected global::System.Web.UI.WebControls.Label lbllong_term_rubbish_stack_rate;
	protected global::System.Web.UI.WebControls.Label lbleducation_fs_indicator;
	protected global::System.Web.UI.WebControls.Label lbleducation_gfa_indicator;
	protected global::System.Web.UI.WebControls.Label lblmedical_fs_indicator;
	protected global::System.Web.UI.WebControls.Label lblmedical_gfa_indicator;
	protected global::System.Web.UI.WebControls.Label lblculture_sports_fs_indicator;
	protected global::System.Web.UI.WebControls.Label lblculture_sports_gfa_indicator;
	protected global::System.Web.UI.WebControls.Label lblcommunity_service_fs_indicator;
	protected global::System.Web.UI.WebControls.Label lblcommunity_service_gfa_indicator;
	protected global::System.Web.UI.WebControls.Label lblcommerce_fs_indicator;
	protected global::System.Web.UI.WebControls.Label lblcommerce_gfa_indicator;
	protected global::System.Web.UI.WebControls.Label lblfarm_produce_fair_fs_indicator;
	protected global::System.Web.UI.WebControls.Label lblfarm_produce_fair_gfa_indicator;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbltciunset11;
	protected global::System.Web.UI.WebControls.Label lbltciunset12;
	protected global::System.Web.UI.WebControls.Label lbltciunset13;
	protected global::System.Web.UI.WebControls.Label lbltciunset14;
	protected global::System.Web.UI.WebControls.Label lbltciunset15;
	protected global::System.Web.UI.WebControls.Label lbltciunset16;
	protected global::System.Web.UI.WebControls.Label lbltciunset17;
	protected global::System.Web.UI.WebControls.Label lbltciunset18;
	protected global::System.Web.UI.WebControls.Label lbltciunset19;
	protected global::System.Web.UI.WebControls.Label lbltciunset20;
	protected global::System.Web.UI.WebControls.Label lbltciunset21;
	protected global::System.Web.UI.WebControls.Label lbltciunset22;
	protected global::System.Web.UI.WebControls.Label lbltciunset23;
	protected global::System.Web.UI.WebControls.Label lbltciunset24;
	protected global::System.Web.UI.WebControls.Label lbltciunset25;
	protected global::System.Web.UI.WebControls.Label lbltciunset26;
	protected global::System.Web.UI.WebControls.Label lbltciunset27;
	protected global::System.Web.UI.WebControls.Label lbltciunset28;
	protected global::System.Web.UI.WebControls.Label lbltciunset29;
	protected global::System.Web.UI.WebControls.Label lbltciunset30;
	protected global::System.Web.UI.WebControls.Label lbltciunset31;
	protected global::System.Web.UI.WebControls.Label lbltciunset32;
	protected global::System.Web.UI.WebControls.Label lbltciunset33;
	protected global::System.Web.UI.WebControls.Label lbltciunset34;
	protected global::System.Web.UI.WebControls.Label lbltciunset35;
	protected global::System.Web.UI.WebControls.Label lbltciunset36;
	protected global::System.Web.UI.WebControls.Label lbltciunset37;
	protected global::System.Web.UI.WebControls.Label lbltciunset38;
	protected global::System.Web.UI.WebControls.Label lbltciunset39;
	protected global::System.Web.UI.WebControls.Label lbltciunset40;
	protected global::System.Web.UI.WebControls.Label lbltciunset41;
	protected global::System.Web.UI.WebControls.Label lbltciunset42;
	protected global::System.Web.UI.WebControls.Label lbltciunset43;
	protected global::System.Web.UI.WebControls.Label lbltciunset44;
	protected global::System.Web.UI.WebControls.Label lbltciunset45;
	protected global::System.Web.UI.WebControls.Label lbltciunset46;
	protected global::System.Web.UI.WebControls.Label lbltciunset47;
	protected global::System.Web.UI.WebControls.Label lbltciunset48;
	protected global::System.Web.UI.WebControls.Label lbltciunset49;
	protected global::System.Web.UI.WebControls.Label lbltciunset50;
	protected global::System.Web.UI.WebControls.Label lbltciunset51;
	protected global::System.Web.UI.WebControls.Label lbltciunset52;
	protected global::System.Web.UI.WebControls.Label lbltciunset53;
	protected global::System.Web.UI.WebControls.Label lbltciunset54;
	protected global::System.Web.UI.WebControls.Label lbltciunset55;
	protected global::System.Web.UI.WebControls.Label lbltciunset56;
	protected global::System.Web.UI.WebControls.Label lbltciunset57;
	protected global::System.Web.UI.WebControls.Label lbltciunset58;
	protected global::System.Web.UI.WebControls.Label lbltciunset59;
	protected global::System.Web.UI.WebControls.Label lbltciunset60;
	protected global::System.Web.UI.WebControls.Label lbltciunset61;
	protected global::System.Web.UI.WebControls.Label lbltciunset62;
	protected global::System.Web.UI.WebControls.Label lbltciunset63;
	protected global::System.Web.UI.WebControls.Label lbltciunset64;
	protected global::System.Web.UI.WebControls.Label lbltciunset65;
	protected global::System.Web.UI.WebControls.Label lbltciunset66;
	protected global::System.Web.UI.WebControls.Label lbltciunset67;
	protected global::System.Web.UI.WebControls.Label lbltciunset68;
	protected global::System.Web.UI.WebControls.Label lbltciunset69;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblhouse_area_per_people;
	protected global::System.Web.UI.WebControls.Label lblcommunity_help_figure;
	protected global::System.Web.UI.WebControls.Label lblcommunity_develop_figure;
	protected global::System.Web.UI.WebControls.Label lblcommunity_engel_coefficient;
	protected global::System.Web.UI.WebControls.Label lblcommunity_gini_coefficient;


       
    }
}
