//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.excel_datatable {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtexcel_name;
	protected global::System.Web.UI.WebControls.Label lbltable_name;
		protected global::System.Web.UI.WebControls.TextBox txttable_start_column;
		protected global::System.Web.UI.WebControls.TextBox txttable_start_row;
		protected global::System.Web.UI.WebControls.TextBox txttable_end_column;
		protected global::System.Web.UI.WebControls.TextBox txttable_end_row;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
