//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_building {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_building_total_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_building_total_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_building_total_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_house_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_house_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_house_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_edu_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_edu_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_edu_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_medical_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_medical_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_medical_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_culture_sports_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_culture_sports_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_culture_sports_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_service_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_service_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_service_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_other_building_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_other_building_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_other_building_num;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset13;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset14;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset15;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset16;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset17;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset18;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset19;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset20;
		protected global::System.Web.UI.WebControls.TextBox txttcbunset21;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
