//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_building {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_building_total_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_building_total_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_building_total_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_house_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_house_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_house_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_edu_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_edu_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_edu_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_medical_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_medical_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_medical_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_culture_sports_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_culture_sports_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_culture_sports_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_service_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_service_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_service_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_other_building_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_other_building_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_other_building_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcbunset1;
	protected global::System.Web.UI.WebControls.Label lbltcbunset2;
	protected global::System.Web.UI.WebControls.Label lbltcbunset3;
	protected global::System.Web.UI.WebControls.Label lbltcbunset4;
	protected global::System.Web.UI.WebControls.Label lbltcbunset5;
	protected global::System.Web.UI.WebControls.Label lbltcbunset6;
	protected global::System.Web.UI.WebControls.Label lbltcbunset7;
	protected global::System.Web.UI.WebControls.Label lbltcbunset8;
	protected global::System.Web.UI.WebControls.Label lbltcbunset9;
	protected global::System.Web.UI.WebControls.Label lbltcbunset10;
	protected global::System.Web.UI.WebControls.Label lbltcbunset11;
	protected global::System.Web.UI.WebControls.Label lbltcbunset12;
	protected global::System.Web.UI.WebControls.Label lbltcbunset13;
	protected global::System.Web.UI.WebControls.Label lbltcbunset14;
	protected global::System.Web.UI.WebControls.Label lbltcbunset15;
	protected global::System.Web.UI.WebControls.Label lbltcbunset16;
	protected global::System.Web.UI.WebControls.Label lbltcbunset17;
	protected global::System.Web.UI.WebControls.Label lbltcbunset18;
	protected global::System.Web.UI.WebControls.Label lbltcbunset19;
	protected global::System.Web.UI.WebControls.Label lbltcbunset20;
	protected global::System.Web.UI.WebControls.Label lbltcbunset21;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
