//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_medical {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_medical_inst_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_medical_inst_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_medical_inst_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_hospital_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_hospital_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_hospital_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_hospital_bed_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_hospital_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_heal_sta_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_heal_sta_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_heal_sta_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_heal_sta_bed_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_heal_sta_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_clinic_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_clinic_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_clinic_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_clinic_bed_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_clinic_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset13;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset14;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset15;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset16;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset17;
		protected global::System.Web.UI.WebControls.TextBox txttcmunset18;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
