//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_medical {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_medical_inst_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_medical_inst_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_medical_inst_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_hospital_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_hospital_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_hospital_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_hospital_bed_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_hospital_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_heal_sta_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_heal_sta_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_heal_sta_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_heal_sta_bed_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_heal_sta_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_clinic_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_clinic_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_clinic_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_clinic_bed_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_clinic_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcmunset1;
	protected global::System.Web.UI.WebControls.Label lbltcmunset2;
	protected global::System.Web.UI.WebControls.Label lbltcmunset3;
	protected global::System.Web.UI.WebControls.Label lbltcmunset4;
	protected global::System.Web.UI.WebControls.Label lbltcmunset5;
	protected global::System.Web.UI.WebControls.Label lbltcmunset6;
	protected global::System.Web.UI.WebControls.Label lbltcmunset7;
	protected global::System.Web.UI.WebControls.Label lbltcmunset8;
	protected global::System.Web.UI.WebControls.Label lbltcmunset9;
	protected global::System.Web.UI.WebControls.Label lbltcmunset10;
	protected global::System.Web.UI.WebControls.Label lbltcmunset11;
	protected global::System.Web.UI.WebControls.Label lbltcmunset12;
	protected global::System.Web.UI.WebControls.Label lbltcmunset13;
	protected global::System.Web.UI.WebControls.Label lbltcmunset14;
	protected global::System.Web.UI.WebControls.Label lbltcmunset15;
	protected global::System.Web.UI.WebControls.Label lbltcmunset16;
	protected global::System.Web.UI.WebControls.Label lbltcmunset17;
	protected global::System.Web.UI.WebControls.Label lbltcmunset18;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
