//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_land {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_total_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_house_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_building_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_greenland_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_industry_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_warehousing_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_traffic_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_municipal_administration_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_other_land_area;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttclunset1;
		protected global::System.Web.UI.WebControls.TextBox txttclunset2;
		protected global::System.Web.UI.WebControls.TextBox txttclunset3;
		protected global::System.Web.UI.WebControls.TextBox txttclunset4;
		protected global::System.Web.UI.WebControls.TextBox txttclunset5;
		protected global::System.Web.UI.WebControls.TextBox txttclunset6;
		protected global::System.Web.UI.WebControls.TextBox txttclunset7;
		protected global::System.Web.UI.WebControls.TextBox txttclunset8;
		protected global::System.Web.UI.WebControls.TextBox txttclunset9;
		protected global::System.Web.UI.WebControls.TextBox txttclunset10;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
