//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_land {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_total_land_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_house_land_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_building_land_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_land_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_greenland_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_industry_land_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_warehousing_land_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_traffic_land_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_municipal_administration_land_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_other_land_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltclunset1;
	protected global::System.Web.UI.WebControls.Label lbltclunset2;
	protected global::System.Web.UI.WebControls.Label lbltclunset3;
	protected global::System.Web.UI.WebControls.Label lbltclunset4;
	protected global::System.Web.UI.WebControls.Label lbltclunset5;
	protected global::System.Web.UI.WebControls.Label lbltclunset6;
	protected global::System.Web.UI.WebControls.Label lbltclunset7;
	protected global::System.Web.UI.WebControls.Label lbltclunset8;
	protected global::System.Web.UI.WebControls.Label lbltclunset9;
	protected global::System.Web.UI.WebControls.Label lbltclunset10;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
