//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.sample {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtsample_house_num;
		protected global::System.Web.UI.WebControls.TextBox txtsample_family_pop;
		protected global::System.Web.UI.WebControls.TextBox txtsample_labor_force_pop;
		protected global::System.Web.UI.WebControls.TextBox txtsample_employment_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtsample_primary_industry_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtsample_secondary_industry_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtsample_tertiary_industry_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtsample_PCDI;
		protected global::System.Web.UI.WebControls.TextBox txtsample_wages_income;
		protected global::System.Web.UI.WebControls.TextBox txtsample_family_run_pure_income;
		protected global::System.Web.UI.WebControls.TextBox txtsample_property_income;
		protected global::System.Web.UI.WebControls.TextBox txtsample_transfer_income;
		protected global::System.Web.UI.WebControls.TextBox txtsample_CONSP;
		protected global::System.Web.UI.WebControls.TextBox txttsunset1;
		protected global::System.Web.UI.WebControls.TextBox txttsunset2;
		protected global::System.Web.UI.WebControls.TextBox txttsunset3;
		protected global::System.Web.UI.WebControls.TextBox txttsunset4;
		protected global::System.Web.UI.WebControls.TextBox txttsunset5;
		protected global::System.Web.UI.WebControls.TextBox txttsunset6;
		protected global::System.Web.UI.WebControls.TextBox txttsunset7;
		protected global::System.Web.UI.WebControls.TextBox txttsunset8;
		protected global::System.Web.UI.WebControls.TextBox txttsunset9;
		protected global::System.Web.UI.WebControls.TextBox txttsunset10;
		protected global::System.Web.UI.WebControls.TextBox txttsunset11;
		protected global::System.Web.UI.WebControls.TextBox txttsunset12;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
