//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.sample {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblsample_house_num;
	protected global::System.Web.UI.WebControls.Label lblsample_family_pop;
	protected global::System.Web.UI.WebControls.Label lblsample_labor_force_pop;
	protected global::System.Web.UI.WebControls.Label lblsample_employment_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblsample_primary_industry_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblsample_secondary_industry_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblsample_tertiary_industry_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblsample_PCDI;
	protected global::System.Web.UI.WebControls.Label lblsample_wages_income;
	protected global::System.Web.UI.WebControls.Label lblsample_family_run_pure_income;
	protected global::System.Web.UI.WebControls.Label lblsample_property_income;
	protected global::System.Web.UI.WebControls.Label lblsample_transfer_income;
	protected global::System.Web.UI.WebControls.Label lblsample_CONSP;
	protected global::System.Web.UI.WebControls.Label lbltsunset1;
	protected global::System.Web.UI.WebControls.Label lbltsunset2;
	protected global::System.Web.UI.WebControls.Label lbltsunset3;
	protected global::System.Web.UI.WebControls.Label lbltsunset4;
	protected global::System.Web.UI.WebControls.Label lbltsunset5;
	protected global::System.Web.UI.WebControls.Label lbltsunset6;
	protected global::System.Web.UI.WebControls.Label lbltsunset7;
	protected global::System.Web.UI.WebControls.Label lbltsunset8;
	protected global::System.Web.UI.WebControls.Label lbltsunset9;
	protected global::System.Web.UI.WebControls.Label lbltsunset10;
	protected global::System.Web.UI.WebControls.Label lbltsunset11;
	protected global::System.Web.UI.WebControls.Label lbltsunset12;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;


       
    }
}
