//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_green_fields {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_green_fields_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_park_green_fields_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_garden_green_fields_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_other_green_fields_area;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_green_fields_bet_dwellings_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_green_fields_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_accomm_green_fields_area;
		protected global::System.Web.UI.WebControls.TextBox txttcgfunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcgfunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcgfunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcgfunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcgfunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcgfunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcgfunset7;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
