//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_green_fields {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_green_fields_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_park_green_fields_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_garden_green_fields_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_other_green_fields_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcommunity_green_fields_bet_dwellings_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_green_fields_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_accomm_green_fields_area;
	protected global::System.Web.UI.WebControls.Label lbltcgfunset1;
	protected global::System.Web.UI.WebControls.Label lbltcgfunset2;
	protected global::System.Web.UI.WebControls.Label lbltcgfunset3;
	protected global::System.Web.UI.WebControls.Label lbltcgfunset4;
	protected global::System.Web.UI.WebControls.Label lbltcgfunset5;
	protected global::System.Web.UI.WebControls.Label lbltcgfunset6;
	protected global::System.Web.UI.WebControls.Label lbltcgfunset7;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
