//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_project {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcounty_name;
	protected global::System.Web.UI.WebControls.Label lblproject_id;
		protected global::System.Web.UI.WebControls.TextBox txtproject_name;
		protected global::System.Web.UI.WebControls.TextBox txtproject_category;
		protected global::System.Web.UI.WebControls.TextBox txtproject_add_time;
		protected global::System.Web.UI.WebControls.TextBox txtproject_total_investment;
		protected global::System.Web.UI.WebControls.TextBox txtproject_proprietor;
		protected global::System.Web.UI.WebControls.TextBox txtplan_to_bulid;
		protected global::System.Web.UI.WebControls.TextBox txtbiding_finish_time;
		protected global::System.Web.UI.WebControls.TextBox txtcontract_period;
		protected global::System.Web.UI.WebControls.TextBox txtproject_start_time;
		protected global::System.Web.UI.WebControls.TextBox txtnot_started_reason_analysis;
		protected global::System.Web.UI.WebControls.TextBox txtcomplete_time;
		protected global::System.Web.UI.WebControls.TextBox txtproject_delay_reason_analysis;
		protected global::System.Web.UI.WebControls.TextBox txtif_major_quality_or_security_accident_happened;
		protected global::System.Web.UI.WebControls.TextBox txtproject_complete_acceptance_time;
		protected global::System.Web.UI.WebControls.TextBox txtcomplete_acceptance_quality_level;
		protected global::System.Web.UI.WebControls.TextBox txtif_transfer;
		protected global::System.Web.UI.WebControls.TextBox txtproject_community_correlation_description;
		protected global::System.Web.UI.WebControls.TextBox txtnote_information;
		protected global::System.Web.UI.WebControls.TextBox txtproject_type;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtmajor_quality_or_security_accident;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txttciunset10;
		protected global::System.Web.UI.WebControls.TextBox txttciunset11;
		protected global::System.Web.UI.WebControls.TextBox txttciunset12;
		protected global::System.Web.UI.WebControls.TextBox txttciunset13;
		protected global::System.Web.UI.WebControls.TextBox txttciunset14;
		protected global::System.Web.UI.WebControls.TextBox txttciunset15;
		protected global::System.Web.UI.WebControls.TextBox txttciunset16;
		protected global::System.Web.UI.WebControls.TextBox txttciunset17;
		protected global::System.Web.UI.WebControls.TextBox txttciunset18;
		protected global::System.Web.UI.WebControls.TextBox txttciunset19;
		protected global::System.Web.UI.WebControls.TextBox txttciunset20;
		protected global::System.Web.UI.WebControls.TextBox txttciunset21;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
