//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_project {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcounty_name;
	protected global::System.Web.UI.WebControls.Label lblproject_id;
	protected global::System.Web.UI.WebControls.Label lblproject_name;
	protected global::System.Web.UI.WebControls.Label lblproject_category;
	protected global::System.Web.UI.WebControls.Label lblproject_add_time;
	protected global::System.Web.UI.WebControls.Label lblproject_total_investment;
	protected global::System.Web.UI.WebControls.Label lblproject_proprietor;
	protected global::System.Web.UI.WebControls.Label lblplan_to_bulid;
	protected global::System.Web.UI.WebControls.Label lblbiding_finish_time;
	protected global::System.Web.UI.WebControls.Label lblcontract_period;
	protected global::System.Web.UI.WebControls.Label lblproject_start_time;
	protected global::System.Web.UI.WebControls.Label lblnot_started_reason_analysis;
	protected global::System.Web.UI.WebControls.Label lblcomplete_time;
	protected global::System.Web.UI.WebControls.Label lblproject_delay_reason_analysis;
	protected global::System.Web.UI.WebControls.Label lblif_major_quality_or_security_accident_happened;
	protected global::System.Web.UI.WebControls.Label lblproject_complete_acceptance_time;
	protected global::System.Web.UI.WebControls.Label lblcomplete_acceptance_quality_level;
	protected global::System.Web.UI.WebControls.Label lblif_transfer;
	protected global::System.Web.UI.WebControls.Label lblproject_community_correlation_description;
	protected global::System.Web.UI.WebControls.Label lblnote_information;
	protected global::System.Web.UI.WebControls.Label lblproject_type;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblmajor_quality_or_security_accident;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbltciunset11;
	protected global::System.Web.UI.WebControls.Label lbltciunset12;
	protected global::System.Web.UI.WebControls.Label lbltciunset13;
	protected global::System.Web.UI.WebControls.Label lbltciunset14;
	protected global::System.Web.UI.WebControls.Label lbltciunset15;
	protected global::System.Web.UI.WebControls.Label lbltciunset16;
	protected global::System.Web.UI.WebControls.Label lbltciunset17;
	protected global::System.Web.UI.WebControls.Label lbltciunset18;
	protected global::System.Web.UI.WebControls.Label lbltciunset19;
	protected global::System.Web.UI.WebControls.Label lbltciunset20;
	protected global::System.Web.UI.WebControls.Label lbltciunset21;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
