//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.project_capital {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtproject_id;
		protected global::System.Web.UI.WebControls.TextBox txtproject_name;
		protected global::System.Web.UI.WebControls.TextBox txtfurnished_type;
		protected global::System.Web.UI.WebControls.TextBox txttotal_investment;
		protected global::System.Web.UI.WebControls.TextBox txtTTG_follow_up_work_approved_special_subsidies;
		protected global::System.Web.UI.WebControls.TextBox txtplan_counterparts_support_funds;
		protected global::System.Web.UI.WebControls.TextBox txtother_matching_funds;
		protected global::System.Web.UI.WebControls.TextBox txtother_funds;
		protected global::System.Web.UI.WebControls.TextBox txttime;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
