//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.project_capital {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblproject_id;
	protected global::System.Web.UI.WebControls.Label lblproject_name;
	protected global::System.Web.UI.WebControls.Label lblfurnished_type;
	protected global::System.Web.UI.WebControls.Label lbltotal_investment;
	protected global::System.Web.UI.WebControls.Label lblTTG_follow_up_work_approved_special_subsidies;
	protected global::System.Web.UI.WebControls.Label lblplan_counterparts_support_funds;
	protected global::System.Web.UI.WebControls.Label lblother_matching_funds;
	protected global::System.Web.UI.WebControls.Label lblother_funds;
	protected global::System.Web.UI.WebControls.Label lbltime;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
