//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_bet_dwellings_road_problem_finished {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_bet_dwellings_maintain_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_bet_dwellings_harden_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_stairways_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_stairways_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pavement_maintain_len;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pavement_parapet_matain_len;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_pavement_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_pavement_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_pavement_num_f_update;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_pavement_area_f_update;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_stairways_num_f_update;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_stairways_area_f_update;


       
    }
}
