//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_social_insurance {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_urban_min_living_sec_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_very_poor_household_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_large_med_resv_immg_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_chongqing_immg_poor_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_medicare_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_endow_insu_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unemp_insu_pop;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcsiunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcsiunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcsiunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcsiunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcsiunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcsiunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcsiunset7;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtpoor_people_rate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
