//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_social_insurance {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_urban_min_living_sec_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_very_poor_household_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_large_med_resv_immg_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_chongqing_immg_poor_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_medicare_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_endow_insu_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_unemp_insu_pop;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcsiunset1;
	protected global::System.Web.UI.WebControls.Label lbltcsiunset2;
	protected global::System.Web.UI.WebControls.Label lbltcsiunset3;
	protected global::System.Web.UI.WebControls.Label lbltcsiunset4;
	protected global::System.Web.UI.WebControls.Label lbltcsiunset5;
	protected global::System.Web.UI.WebControls.Label lbltcsiunset6;
	protected global::System.Web.UI.WebControls.Label lbltcsiunset7;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lblpoor_people_rate;


       
    }
}
