//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_security {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unit_can_build_guard_room_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unit_with_guard_room_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unit_can_install_mf_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unit_with_mf_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unit_can_build_fence_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unit_with_fence_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_emergency_shelter_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_civil_air_defence_facilities_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_civil_air_defence_facilities_area;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_unit_can_build_gate_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_with_gate_num;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcsunset11;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
