//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_security {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_unit_can_build_guard_room_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_unit_with_guard_room_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_unit_can_install_mf_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_unit_with_mf_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_unit_can_build_fence_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_unit_with_fence_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_emergency_shelter_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_civil_air_defence_facilities_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_civil_air_defence_facilities_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcommunity_unit_can_build_gate_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_with_gate_num;
	protected global::System.Web.UI.WebControls.Label lbltcsunset1;
	protected global::System.Web.UI.WebControls.Label lbltcsunset2;
	protected global::System.Web.UI.WebControls.Label lbltcsunset3;
	protected global::System.Web.UI.WebControls.Label lbltcsunset4;
	protected global::System.Web.UI.WebControls.Label lbltcsunset5;
	protected global::System.Web.UI.WebControls.Label lbltcsunset6;
	protected global::System.Web.UI.WebControls.Label lbltcsunset7;
	protected global::System.Web.UI.WebControls.Label lbltcsunset8;
	protected global::System.Web.UI.WebControls.Label lbltcsunset9;
	protected global::System.Web.UI.WebControls.Label lbltcsunset10;
	protected global::System.Web.UI.WebControls.Label lbltcsunset11;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
