//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_water_supply {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_supply_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_supply_main_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_supply_pipe_branch_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_supply_service_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_supply_consumption;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_per_capita_water_supply_consumption;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcwsunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcwsunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcwsunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcwsunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcwsunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcwsunset6;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
