//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_water_supply {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_supply_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_supply_main_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_supply_pipe_branch_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_supply_service_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_supply_consumption;
	protected global::System.Web.UI.WebControls.Label lblcommunity_per_capita_water_supply_consumption;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcwsunset1;
	protected global::System.Web.UI.WebControls.Label lbltcwsunset2;
	protected global::System.Web.UI.WebControls.Label lbltcwsunset3;
	protected global::System.Web.UI.WebControls.Label lbltcwsunset4;
	protected global::System.Web.UI.WebControls.Label lbltcwsunset5;
	protected global::System.Web.UI.WebControls.Label lbltcwsunset6;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
