//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_environmental_hygiene {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_refuse_transfer_station_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_refuse_transfer_station_dis_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_refuse_collection_point_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_dustbin_num;
		protected global::System.Web.UI.WebControls.TextBox txtrubbish_produce_amount;
		protected global::System.Web.UI.WebControls.TextBox txtlive_rubbish_produce_year_amount;
		protected global::System.Web.UI.WebControls.TextBox txtsolid_rubbish_produce_amount;
		protected global::System.Web.UI.WebControls.TextBox txtenvironmental_fee_charge_amount;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_space_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_inside_300m_num;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_cover_road_length;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcehunset11;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_toilet_area_num;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
