//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_environmental_hygiene {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_refuse_transfer_station_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_refuse_transfer_station_dis_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_refuse_collection_point_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_dustbin_num;
	protected global::System.Web.UI.WebControls.Label lblrubbish_produce_amount;
	protected global::System.Web.UI.WebControls.Label lbllive_rubbish_produce_year_amount;
	protected global::System.Web.UI.WebControls.Label lblsolid_rubbish_produce_amount;
	protected global::System.Web.UI.WebControls.Label lblenvironmental_fee_charge_amount;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_toilet_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_toilet_space_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_toilet_inside_300m_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_toilet_cover_road_length;
	protected global::System.Web.UI.WebControls.Label lbltcehunset1;
	protected global::System.Web.UI.WebControls.Label lbltcehunset2;
	protected global::System.Web.UI.WebControls.Label lbltcehunset3;
	protected global::System.Web.UI.WebControls.Label lbltcehunset4;
	protected global::System.Web.UI.WebControls.Label lbltcehunset5;
	protected global::System.Web.UI.WebControls.Label lbltcehunset6;
	protected global::System.Web.UI.WebControls.Label lbltcehunset7;
	protected global::System.Web.UI.WebControls.Label lbltcehunset8;
	protected global::System.Web.UI.WebControls.Label lbltcehunset9;
	protected global::System.Web.UI.WebControls.Label lbltcehunset10;
	protected global::System.Web.UI.WebControls.Label lbltcehunset11;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_toilet_area_num;


       
    }
}
