//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_road {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_width_bet_14_and_24_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_width_bet_14_and_24_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_width_bet_10_and_14_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_width_bet_10_and_14_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_width_bet_6_and_9_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_width_bet_6_and_9_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_width_bet_3_and_5_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_width_bet_3_and_5_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_pavement_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_pavement_colorful_brick_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_bet_dwellings_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_bet_dwellings_lengthcommunity_road_bet_dwellings_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pavement_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pavement_area;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_num;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset13;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset14;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset15;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset16;
		protected global::System.Web.UI.WebControls.TextBox txttcrunset17;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
