//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_road {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_width_bet_14_and_24_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_width_bet_14_and_24_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_width_bet_10_and_14_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_width_bet_10_and_14_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_width_bet_6_and_9_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_width_bet_6_and_9_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_width_bet_3_and_5_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_width_bet_3_and_5_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_pavement_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_pavement_colorful_brick_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_bet_dwellings_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_bet_dwellings_lengthcommunity_road_bet_dwellings_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pavement_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pavement_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcommunity_road_num;
	protected global::System.Web.UI.WebControls.Label lbltcrunset1;
	protected global::System.Web.UI.WebControls.Label lbltcrunset2;
	protected global::System.Web.UI.WebControls.Label lbltcrunset3;
	protected global::System.Web.UI.WebControls.Label lbltcrunset4;
	protected global::System.Web.UI.WebControls.Label lbltcrunset5;
	protected global::System.Web.UI.WebControls.Label lbltcrunset6;
	protected global::System.Web.UI.WebControls.Label lbltcrunset7;
	protected global::System.Web.UI.WebControls.Label lbltcrunset8;
	protected global::System.Web.UI.WebControls.Label lbltcrunset9;
	protected global::System.Web.UI.WebControls.Label lbltcrunset10;
	protected global::System.Web.UI.WebControls.Label lbltcrunset11;
	protected global::System.Web.UI.WebControls.Label lbltcrunset12;
	protected global::System.Web.UI.WebControls.Label lbltcrunset13;
	protected global::System.Web.UI.WebControls.Label lbltcrunset14;
	protected global::System.Web.UI.WebControls.Label lbltcrunset15;
	protected global::System.Web.UI.WebControls.Label lbltcrunset16;
	protected global::System.Web.UI.WebControls.Label lbltcrunset17;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
