//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_commerce_service_problem {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fill_type;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_shopping_inc_unit_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_shopping_inc_people_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_fm_insuf_area_unit_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_fm_insuf_area_people_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lack_fm;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
