//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.effect_indicator {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtstructure_safe_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtroof_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtwall_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtslope_safe_rate;
		protected global::System.Web.UI.WebControls.TextBox txtconcil_house_validate;
		protected global::System.Web.UI.WebControls.TextBox txtroad_link_degree;
		protected global::System.Web.UI.WebControls.TextBox txtroad_good_degree;
		protected global::System.Web.UI.WebControls.TextBox txttraffic_validate;
		protected global::System.Web.UI.WebControls.TextBox txtwater_capcity_degree;
		protected global::System.Web.UI.WebControls.TextBox txtwater_pipe_net_good_degree;
		protected global::System.Web.UI.WebControls.TextBox txtone_hou_one_water_meter_rate;
		protected global::System.Web.UI.WebControls.TextBox txtwater_supply_validate;
		protected global::System.Web.UI.WebControls.TextBox txtelec_capcity_degree;
		protected global::System.Web.UI.WebControls.TextBox txtelec_wire_safe_degree;
		protected global::System.Web.UI.WebControls.TextBox txtone_hou_one_elec_meter_rate;
		protected global::System.Web.UI.WebControls.TextBox txtelec_supply_validate;
		protected global::System.Web.UI.WebControls.TextBox txtroad_light_suff_degree;
		protected global::System.Web.UI.WebControls.TextBox txtpassway_light_suff_degree;
		protected global::System.Web.UI.WebControls.TextBox txtlight_validate;
		protected global::System.Web.UI.WebControls.TextBox txtoutdoors_ff_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtindoors_ff_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtff_way_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtff_validate;
		protected global::System.Web.UI.WebControls.TextBox txtbasic_facility_validate;
		protected global::System.Web.UI.WebControls.TextBox txtrefuse_collect_rate;
		protected global::System.Web.UI.WebControls.TextBox txttoilet_cover_degree;
		protected global::System.Web.UI.WebControls.TextBox txtsanitation_validate;
		protected global::System.Web.UI.WebControls.TextBox txtsewage_collect_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdrain_safe_degree;
		protected global::System.Web.UI.WebControls.TextBox txtdrain_validate;
		protected global::System.Web.UI.WebControls.TextBox txtgreen_validate;
		protected global::System.Web.UI.WebControls.TextBox txtenvironment_validate;
		protected global::System.Web.UI.WebControls.TextBox txtservice_gfs_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtkindergarten_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtmedical_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtparking_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtCVS_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtvegetable_market_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommerce_validate;
		protected global::System.Web.UI.WebControls.TextBox txtcul_fitness_facility_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtolder_facility_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtpublic_service_good_rate;
		protected global::System.Web.UI.WebControls.TextBox txtshop_front_use_rate;
		protected global::System.Web.UI.WebControls.TextBox txtshop_front_rent_level;
		protected global::System.Web.UI.WebControls.TextBox txtshop_validate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_validate;
		protected global::System.Web.UI.WebControls.TextBox txtindicator1;
		protected global::System.Web.UI.WebControls.TextBox txtindicator2;
		protected global::System.Web.UI.WebControls.TextBox txtindicator3;
		protected global::System.Web.UI.WebControls.TextBox txtindicator4;
		protected global::System.Web.UI.WebControls.TextBox txtindicator5;
		protected global::System.Web.UI.WebControls.TextBox txtindicator6;
		protected global::System.Web.UI.WebControls.TextBox txtindicator7;
		protected global::System.Web.UI.WebControls.TextBox txtindicator8;
		protected global::System.Web.UI.WebControls.TextBox txtindicator9;
		protected global::System.Web.UI.WebControls.TextBox txtindicator10;
		protected global::System.Web.UI.WebControls.TextBox txtindicator11;
		protected global::System.Web.UI.WebControls.TextBox txtindicator12;
		protected global::System.Web.UI.WebControls.TextBox txtindicator13;
		protected global::System.Web.UI.WebControls.TextBox txtindicator14;
		protected global::System.Web.UI.WebControls.TextBox txtindicator15;
		protected global::System.Web.UI.WebControls.TextBox txtindicator16;
		protected global::System.Web.UI.WebControls.TextBox txtindicator17;
		protected global::System.Web.UI.WebControls.TextBox txtindicator18;
		protected global::System.Web.UI.WebControls.TextBox txtindicator19;
		protected global::System.Web.UI.WebControls.TextBox txtindicator20;
		protected global::System.Web.UI.WebControls.TextBox txtindicator21;
		protected global::System.Web.UI.WebControls.TextBox txtindicator22;
		protected global::System.Web.UI.WebControls.TextBox txtindicator23;
		protected global::System.Web.UI.WebControls.TextBox txtindicator24;
		protected global::System.Web.UI.WebControls.TextBox txtindicator25;
		protected global::System.Web.UI.WebControls.TextBox txtindicator26;
		protected global::System.Web.UI.WebControls.TextBox txtindicator27;
		protected global::System.Web.UI.WebControls.TextBox txtindicator28;
		protected global::System.Web.UI.WebControls.TextBox txtindicator29;
		protected global::System.Web.UI.WebControls.TextBox txtindicator30;
		protected global::System.Web.UI.WebControls.TextBox txtindicator31;
		protected global::System.Web.UI.WebControls.TextBox txtindicator32;
		protected global::System.Web.UI.WebControls.TextBox txtindicator33;
		protected global::System.Web.UI.WebControls.TextBox txtindicator34;
		protected global::System.Web.UI.WebControls.TextBox txtindicator35;
		protected global::System.Web.UI.WebControls.TextBox txtindicator36;
		protected global::System.Web.UI.WebControls.TextBox txtindicator37;
		protected global::System.Web.UI.WebControls.TextBox txtindicator38;
		protected global::System.Web.UI.WebControls.TextBox txtindicator39;
		protected global::System.Web.UI.WebControls.TextBox txtindicator40;
		protected global::System.Web.UI.WebControls.TextBox txtindicator41;
		protected global::System.Web.UI.WebControls.TextBox txtindicator42;
		protected global::System.Web.UI.WebControls.TextBox txtindicator43;
		protected global::System.Web.UI.WebControls.TextBox txtindicator44;
		protected global::System.Web.UI.WebControls.TextBox txtindicator45;
		protected global::System.Web.UI.WebControls.TextBox txtindicator46;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtlabor_employment_rate;
		protected global::System.Web.UI.WebControls.TextBox txtdisposable_money_per_people;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
