//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.effect_indicator {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblstructure_safe_good_rate;
	protected global::System.Web.UI.WebControls.Label lblroof_good_rate;
	protected global::System.Web.UI.WebControls.Label lblwall_good_rate;
	protected global::System.Web.UI.WebControls.Label lblslope_safe_rate;
	protected global::System.Web.UI.WebControls.Label lblconcil_house_validate;
	protected global::System.Web.UI.WebControls.Label lblroad_link_degree;
	protected global::System.Web.UI.WebControls.Label lblroad_good_degree;
	protected global::System.Web.UI.WebControls.Label lbltraffic_validate;
	protected global::System.Web.UI.WebControls.Label lblwater_capcity_degree;
	protected global::System.Web.UI.WebControls.Label lblwater_pipe_net_good_degree;
	protected global::System.Web.UI.WebControls.Label lblone_hou_one_water_meter_rate;
	protected global::System.Web.UI.WebControls.Label lblwater_supply_validate;
	protected global::System.Web.UI.WebControls.Label lblelec_capcity_degree;
	protected global::System.Web.UI.WebControls.Label lblelec_wire_safe_degree;
	protected global::System.Web.UI.WebControls.Label lblone_hou_one_elec_meter_rate;
	protected global::System.Web.UI.WebControls.Label lblelec_supply_validate;
	protected global::System.Web.UI.WebControls.Label lblroad_light_suff_degree;
	protected global::System.Web.UI.WebControls.Label lblpassway_light_suff_degree;
	protected global::System.Web.UI.WebControls.Label lbllight_validate;
	protected global::System.Web.UI.WebControls.Label lbloutdoors_ff_good_rate;
	protected global::System.Web.UI.WebControls.Label lblindoors_ff_good_rate;
	protected global::System.Web.UI.WebControls.Label lblff_way_good_rate;
	protected global::System.Web.UI.WebControls.Label lblff_validate;
	protected global::System.Web.UI.WebControls.Label lblbasic_facility_validate;
	protected global::System.Web.UI.WebControls.Label lblrefuse_collect_rate;
	protected global::System.Web.UI.WebControls.Label lbltoilet_cover_degree;
	protected global::System.Web.UI.WebControls.Label lblsanitation_validate;
	protected global::System.Web.UI.WebControls.Label lblsewage_collect_rate;
	protected global::System.Web.UI.WebControls.Label lbldrain_safe_degree;
	protected global::System.Web.UI.WebControls.Label lbldrain_validate;
	protected global::System.Web.UI.WebControls.Label lblgreen_validate;
	protected global::System.Web.UI.WebControls.Label lblenvironment_validate;
	protected global::System.Web.UI.WebControls.Label lblservice_gfs_good_rate;
	protected global::System.Web.UI.WebControls.Label lblkindergarten_good_rate;
	protected global::System.Web.UI.WebControls.Label lblmedical_good_rate;
	protected global::System.Web.UI.WebControls.Label lblparking_good_rate;
	protected global::System.Web.UI.WebControls.Label lblCVS_good_rate;
	protected global::System.Web.UI.WebControls.Label lblvegetable_market_good_rate;
	protected global::System.Web.UI.WebControls.Label lblcommerce_validate;
	protected global::System.Web.UI.WebControls.Label lblcul_fitness_facility_good_rate;
	protected global::System.Web.UI.WebControls.Label lblolder_facility_good_rate;
	protected global::System.Web.UI.WebControls.Label lblpublic_service_good_rate;
	protected global::System.Web.UI.WebControls.Label lblshop_front_use_rate;
	protected global::System.Web.UI.WebControls.Label lblshop_front_rent_level;
	protected global::System.Web.UI.WebControls.Label lblshop_validate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_validate;
	protected global::System.Web.UI.WebControls.Label lblindicator1;
	protected global::System.Web.UI.WebControls.Label lblindicator2;
	protected global::System.Web.UI.WebControls.Label lblindicator3;
	protected global::System.Web.UI.WebControls.Label lblindicator4;
	protected global::System.Web.UI.WebControls.Label lblindicator5;
	protected global::System.Web.UI.WebControls.Label lblindicator6;
	protected global::System.Web.UI.WebControls.Label lblindicator7;
	protected global::System.Web.UI.WebControls.Label lblindicator8;
	protected global::System.Web.UI.WebControls.Label lblindicator9;
	protected global::System.Web.UI.WebControls.Label lblindicator10;
	protected global::System.Web.UI.WebControls.Label lblindicator11;
	protected global::System.Web.UI.WebControls.Label lblindicator12;
	protected global::System.Web.UI.WebControls.Label lblindicator13;
	protected global::System.Web.UI.WebControls.Label lblindicator14;
	protected global::System.Web.UI.WebControls.Label lblindicator15;
	protected global::System.Web.UI.WebControls.Label lblindicator16;
	protected global::System.Web.UI.WebControls.Label lblindicator17;
	protected global::System.Web.UI.WebControls.Label lblindicator18;
	protected global::System.Web.UI.WebControls.Label lblindicator19;
	protected global::System.Web.UI.WebControls.Label lblindicator20;
	protected global::System.Web.UI.WebControls.Label lblindicator21;
	protected global::System.Web.UI.WebControls.Label lblindicator22;
	protected global::System.Web.UI.WebControls.Label lblindicator23;
	protected global::System.Web.UI.WebControls.Label lblindicator24;
	protected global::System.Web.UI.WebControls.Label lblindicator25;
	protected global::System.Web.UI.WebControls.Label lblindicator26;
	protected global::System.Web.UI.WebControls.Label lblindicator27;
	protected global::System.Web.UI.WebControls.Label lblindicator28;
	protected global::System.Web.UI.WebControls.Label lblindicator29;
	protected global::System.Web.UI.WebControls.Label lblindicator30;
	protected global::System.Web.UI.WebControls.Label lblindicator31;
	protected global::System.Web.UI.WebControls.Label lblindicator32;
	protected global::System.Web.UI.WebControls.Label lblindicator33;
	protected global::System.Web.UI.WebControls.Label lblindicator34;
	protected global::System.Web.UI.WebControls.Label lblindicator35;
	protected global::System.Web.UI.WebControls.Label lblindicator36;
	protected global::System.Web.UI.WebControls.Label lblindicator37;
	protected global::System.Web.UI.WebControls.Label lblindicator38;
	protected global::System.Web.UI.WebControls.Label lblindicator39;
	protected global::System.Web.UI.WebControls.Label lblindicator40;
	protected global::System.Web.UI.WebControls.Label lblindicator41;
	protected global::System.Web.UI.WebControls.Label lblindicator42;
	protected global::System.Web.UI.WebControls.Label lblindicator43;
	protected global::System.Web.UI.WebControls.Label lblindicator44;
	protected global::System.Web.UI.WebControls.Label lblindicator45;
	protected global::System.Web.UI.WebControls.Label lblindicator46;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lbllabor_employment_rate;
	protected global::System.Web.UI.WebControls.Label lbldisposable_money_per_people;


       
    }
}
