//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_education {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_edu_inst_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_edu_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_edu_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pri_kdg_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_stu_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_class_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_actv_room_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_otd_actv_spa_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_greenland_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_kdg_dist_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prim_school_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prim_school_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prim_school_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prim_school_stu_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prim_school_class_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prim_school_plg_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_prim_school_dist_ots;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_mid_school_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_mid_school_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_mid_school_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_mid_school_stu_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_mid_school_class_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_mid_school_plg_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_mid_school_dist_ots;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttceunset1;
		protected global::System.Web.UI.WebControls.TextBox txttceunset2;
		protected global::System.Web.UI.WebControls.TextBox txttceunset3;
		protected global::System.Web.UI.WebControls.TextBox txttceunset4;
		protected global::System.Web.UI.WebControls.TextBox txttceunset5;
		protected global::System.Web.UI.WebControls.TextBox txttceunset6;
		protected global::System.Web.UI.WebControls.TextBox txttceunset7;
		protected global::System.Web.UI.WebControls.TextBox txttceunset8;
		protected global::System.Web.UI.WebControls.TextBox txttceunset9;
		protected global::System.Web.UI.WebControls.TextBox txttceunset10;
		protected global::System.Web.UI.WebControls.TextBox txttceunset11;
		protected global::System.Web.UI.WebControls.TextBox txttceunset12;
		protected global::System.Web.UI.WebControls.TextBox txttceunset13;
		protected global::System.Web.UI.WebControls.TextBox txttceunset14;
		protected global::System.Web.UI.WebControls.TextBox txttceunset15;
		protected global::System.Web.UI.WebControls.TextBox txttceunset16;
		protected global::System.Web.UI.WebControls.TextBox txttceunset17;
		protected global::System.Web.UI.WebControls.TextBox txttceunset18;
		protected global::System.Web.UI.WebControls.TextBox txttceunset19;
		protected global::System.Web.UI.WebControls.TextBox txttceunset20;
		protected global::System.Web.UI.WebControls.TextBox txttceunset21;
		protected global::System.Web.UI.WebControls.TextBox txttceunset22;
		protected global::System.Web.UI.WebControls.TextBox txttceunset23;
		protected global::System.Web.UI.WebControls.TextBox txttceunset24;
		protected global::System.Web.UI.WebControls.TextBox txttceunset25;
		protected global::System.Web.UI.WebControls.TextBox txttceunset26;
		protected global::System.Web.UI.WebControls.TextBox txttceunset27;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
