//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_education {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_edu_inst_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_edu_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_edu_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pri_kdg_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_stu_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_class_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_actv_room_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_otd_actv_spa_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_greenland_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_kdg_dist_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prim_school_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prim_school_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prim_school_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prim_school_stu_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prim_school_class_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prim_school_plg_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_prim_school_dist_ots;
	protected global::System.Web.UI.WebControls.Label lblcommunity_mid_school_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_mid_school_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_mid_school_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_mid_school_stu_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_mid_school_class_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_mid_school_plg_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_mid_school_dist_ots;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltceunset1;
	protected global::System.Web.UI.WebControls.Label lbltceunset2;
	protected global::System.Web.UI.WebControls.Label lbltceunset3;
	protected global::System.Web.UI.WebControls.Label lbltceunset4;
	protected global::System.Web.UI.WebControls.Label lbltceunset5;
	protected global::System.Web.UI.WebControls.Label lbltceunset6;
	protected global::System.Web.UI.WebControls.Label lbltceunset7;
	protected global::System.Web.UI.WebControls.Label lbltceunset8;
	protected global::System.Web.UI.WebControls.Label lbltceunset9;
	protected global::System.Web.UI.WebControls.Label lbltceunset10;
	protected global::System.Web.UI.WebControls.Label lbltceunset11;
	protected global::System.Web.UI.WebControls.Label lbltceunset12;
	protected global::System.Web.UI.WebControls.Label lbltceunset13;
	protected global::System.Web.UI.WebControls.Label lbltceunset14;
	protected global::System.Web.UI.WebControls.Label lbltceunset15;
	protected global::System.Web.UI.WebControls.Label lbltceunset16;
	protected global::System.Web.UI.WebControls.Label lbltceunset17;
	protected global::System.Web.UI.WebControls.Label lbltceunset18;
	protected global::System.Web.UI.WebControls.Label lbltceunset19;
	protected global::System.Web.UI.WebControls.Label lbltceunset20;
	protected global::System.Web.UI.WebControls.Label lbltceunset21;
	protected global::System.Web.UI.WebControls.Label lbltceunset22;
	protected global::System.Web.UI.WebControls.Label lbltceunset23;
	protected global::System.Web.UI.WebControls.Label lbltceunset24;
	protected global::System.Web.UI.WebControls.Label lbltceunset25;
	protected global::System.Web.UI.WebControls.Label lbltceunset26;
	protected global::System.Web.UI.WebControls.Label lbltceunset27;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
