//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_lighting_problem {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_fill_type;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_wout_slamp_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_wout_slamp_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_lack_slamp_insuf_light_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_road_lack_slamp_insuf_light_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_outground_insuf_light_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_corridor_lc_damage_res_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_corridor_light_damage_house_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_insuf_light_res_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_slamp_damage_num;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txttciunset10;
		protected global::System.Web.UI.WebControls.TextBox txttciunset11;
		protected global::System.Web.UI.WebControls.TextBox txttciunset12;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
