//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.wcommunity {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtwcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtwcommunity_name;
		protected global::System.Web.UI.WebControls.TextBox txtkindergarten_capacity;
		protected global::System.Web.UI.WebControls.TextBox txtintegrated_management_building_area;
		protected global::System.Web.UI.WebControls.TextBox txtmedical_bed_num;
		protected global::System.Web.UI.WebControls.TextBox txtparking_space_num;
		protected global::System.Web.UI.WebControls.TextBox txtconvenience_stores_area;
		protected global::System.Web.UI.WebControls.TextBox txtvegetable_market_area;
		protected global::System.Web.UI.WebControls.TextBox txtculture_fitness_facility_area;
		protected global::System.Web.UI.WebControls.TextBox txtfacilities_for_elders_area;
		protected global::System.Web.UI.WebControls.TextBox txttwunset1;
		protected global::System.Web.UI.WebControls.TextBox txttwunset2;
		protected global::System.Web.UI.WebControls.TextBox txttwunset3;
		protected global::System.Web.UI.WebControls.TextBox txttwunset4;
		protected global::System.Web.UI.WebControls.TextBox txttwunset5;
		protected global::System.Web.UI.WebControls.TextBox txttwunset6;
		protected global::System.Web.UI.WebControls.TextBox txttwunset7;
		protected global::System.Web.UI.WebControls.TextBox txttwunset8;
		protected global::System.Web.UI.WebControls.TextBox txttwunset9;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtwcommunity_family_num;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
