//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.wcommunity {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblwcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblwcommunity_name;
	protected global::System.Web.UI.WebControls.Label lblkindergarten_capacity;
	protected global::System.Web.UI.WebControls.Label lblintegrated_management_building_area;
	protected global::System.Web.UI.WebControls.Label lblmedical_bed_num;
	protected global::System.Web.UI.WebControls.Label lblparking_space_num;
	protected global::System.Web.UI.WebControls.Label lblconvenience_stores_area;
	protected global::System.Web.UI.WebControls.Label lblvegetable_market_area;
	protected global::System.Web.UI.WebControls.Label lblculture_fitness_facility_area;
	protected global::System.Web.UI.WebControls.Label lblfacilities_for_elders_area;
	protected global::System.Web.UI.WebControls.Label lbltwunset1;
	protected global::System.Web.UI.WebControls.Label lbltwunset2;
	protected global::System.Web.UI.WebControls.Label lbltwunset3;
	protected global::System.Web.UI.WebControls.Label lbltwunset4;
	protected global::System.Web.UI.WebControls.Label lbltwunset5;
	protected global::System.Web.UI.WebControls.Label lbltwunset6;
	protected global::System.Web.UI.WebControls.Label lbltwunset7;
	protected global::System.Web.UI.WebControls.Label lbltwunset8;
	protected global::System.Web.UI.WebControls.Label lbltwunset9;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblwcommunity_family_num;


       
    }
}
