//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_business_pop_problem_finished {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_recon_block_len;
	protected global::System.Web.UI.WebControls.Label lblcommunity_recon_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_recon_shop_front_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_added_market_merchants_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_market_area;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
