//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_concil_house {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_council_buil_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_gfa;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_fs;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_unit_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_floor_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_suite_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_family_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_conhou_people_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcchunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcchunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcchunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcchunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcchunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcchunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcchunset8;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
