//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_concil_house {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_council_buil_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_gfa;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_fs;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_unit_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_floor_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_suite_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_family_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_conhou_people_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcchunset1;
	protected global::System.Web.UI.WebControls.Label lbltcchunset2;
	protected global::System.Web.UI.WebControls.Label lbltcchunset3;
	protected global::System.Web.UI.WebControls.Label lbltcchunset4;
	protected global::System.Web.UI.WebControls.Label lbltcchunset5;
	protected global::System.Web.UI.WebControls.Label lbltcchunset6;
	protected global::System.Web.UI.WebControls.Label lbltcchunset8;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
