//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_shop_front {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_shop_front_in_main_street_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_shop_front_in_collector_street_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_shop_front_in_alley_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_back_street_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_shop_front_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_shop_front_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_run_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_run_shop_front_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_rent_out_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_rent_out_shop_front_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_unused_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_unused_shop_front_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_shop_front_amount;
	protected global::System.Web.UI.WebControls.Label lblcommunity_catering_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_accommodation_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_commodity_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_means_of_production_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_automobile_service_shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_other__shop_front_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_average_rent_of_shop_front;
	protected global::System.Web.UI.WebControls.Label lblcommunity_average_rent_time_of_shop_front;
	protected global::System.Web.UI.WebControls.Label lblcommunity_average_price_shop_front;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;


       
    }
}
