using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace TTG.Web.json1
{
    public class basicFacilityToJson : jsonTools
    {
        private DAL.GET.get_base_facilities gbf;
        public basicFacilityToJson(String province,String county,String community) 
        {
            gbf = new DAL.GET.get_base_facilities(province, county, community);
        }
        private StringBuilder result = new StringBuilder();

        public String getResult()
        {
            result.Append("{");
            addAttribute("basicSituation");
            #region basicSituation
            result.Append("{");
            addAttribute("situation2013");
            #region situation2013
            result.Append("{");
            addAttribute("community_broken_road_num");
            addValue(gbf.Broken_road_num_2013);
            result.Append(",");
            addAttribute("community_sarea_lack_lroad");
            addValue(gbf.Lack_link_num_2013);
            result.Append(",");
            addAttribute("community_road_not_hardening_area");
            addValue(gbf.Not_hard_area_2013);
            result.Append(",");
            addAttribute("community_road_pavement_damage_area_vehicle");
            addValue(gbf.Road_broken_2013);
            result.Append(",");
            addAttribute("community_road_pavement_damage_area_sidewalk");
            addValue(gbf.Sidewalk_broken_2013);
            result.Append(",");
            addAttribute("community_sidewalk_cb_damage_area");
            addValue(gbf.Lack_sidewalk_2013);//改动
            result.Append(",");
            addAttribute("community_insuf_ws_house_num");
            addValue(gbf.Inadequate_water_2013);
            result.Append(",");
            addAttribute("community_insuf_wp_house_num");
            addValue(gbf.Water_pressure_2013);
            result.Append(",");
            addAttribute("community_pipe_damage_length");
            addValue(gbf.Pipe_damage_2013);
            result.Append(",");
            addAttribute("community_not_imple_ohot_house_num");
            addValue(gbf.Not_one_one_2013);
            result.Append(",");
            addAttribute("community_transformer_cap_ins_hou_num");
            addValue(gbf.Elec_inade_2013);
            result.Append(",");
            addAttribute("community_senescent_elec_wireways_length");
            addValue(gbf.Link_damage_2013);
            result.Append(",");
            addAttribute("community_no_one_hou_one_meter_hou_num");
            addValue(gbf.Not_e_one_one_2013);
            result.Append(",");
            addAttribute("community_road_wout_slamp_num");
            addValue(gbf.No_light_now);
            result.Append(",");
            addAttribute("community_road_lack_slamp_insuf_light_num");
            addValue(gbf.Less_light_now);
            result.Append(",");
            addAttribute("community_corridor_light_damage_house_num");
            addValue(gbf.Light_damage_2013);
            result.Append(",");
            addAttribute("community_road_lack_outdoor_fh_length");
            addValue(gbf.Out_ff_less_2013);
            result.Append(",");
            addAttribute("community_lack_indoor_fh_building_num");
            addValue(gbf.In_ff_less_2013);
            result.Append(",");
            addAttribute("community_ff_aisle_not_standard_len");
            addValue(gbf.Exits_not_com_2013);
            result.Append("},");
            #endregion
            addAttribute("situationNow");
            #region situationNow
            result.Append("{");
            addAttribute("community_broken_road_num");
            addValue(gbf.Broken_road_num_now);
            result.Append(",");
            addAttribute("community_sarea_lack_lroad");
            addValue(gbf.Lack_link_num_now);
            result.Append(",");
            addAttribute("community_road_not_hardening_area");
            addValue(gbf.Not_hard_area_now);
            result.Append(",");
            addAttribute("community_road_pavement_damage_area_vehicle");
            addValue(gbf.Road_broken_now);
            result.Append(",");
            addAttribute("community_road_pavement_damage_area_sidewalk");
            addValue(gbf.Sidewalk_broken_now);
            result.Append(",");
            addAttribute("community_sidewalk_cb_damage_area");
            addValue(gbf.Lack_sidewalk_now);//todo
            result.Append(",");
            addAttribute("community_insuf_ws_house_num");
            addValue(gbf.Inadequate_water_now);
            result.Append(",");
            addAttribute("community_insuf_wp_house_num");
            addValue(gbf.Water_pressure_now);//todo
            result.Append(",");
            addAttribute("community_pipe_damage_length");
            addValue(gbf.Pipe_damage_now);
            result.Append(",");
            addAttribute("community_not_imple_ohot_house_num");
            addValue(gbf.Not_one_one_now);//todo
            result.Append(",");
            addAttribute("community_transformer_cap_ins_hou_num");
            addValue(gbf.Elec_inade_now);//todo
            result.Append(",");
            addAttribute("community_senescent_elec_wireways_length");
            addValue(gbf.Link_damage_2013);
            result.Append(",");
            addAttribute("community_no_one_hou_one_meter_hou_num");
            addValue(gbf.Not_e_one_one_now);
            result.Append(",");
            addAttribute("community_road_wout_slamp_num");
            addValue(gbf.No_light_2013);//todo
            result.Append(",");
            addAttribute("community_road_lack_slamp_insuf_light_num");
            addValue(gbf.Less_light_2013);//todo
            result.Append(",");
            addAttribute("community_corridor_light_damage_house_num");
            addValue(gbf.Light_damage_now);
            result.Append(",");
            addAttribute("community_road_lack_outdoor_fh_length");
            addValue(gbf.Out_ff_less_now);
            result.Append(",");
            addAttribute("community_lack_indoor_fh_building_num");
            addValue(gbf.In_ff_less_now);
            result.Append(",");
            addAttribute("community_ff_aisle_not_standard_len");
            addValue(gbf.Exits_not_com_now);
            result.Append("}");
            #endregion
            result.Append("},");
            #endregion
            addAttribute("implementSituation");
            #region implementSituation
            result.Append("{");
            addAttribute("plan");
            #region
            result.Append("{");
            addAttribute("community_added_road_num");
            addValue(gbf.Add_link_num_plan);
            result.Append(",");
            addAttribute("community_added_vehicles_road_area");
            addValue(gbf.Add_road_area_plan);
            result.Append(",");
            addAttribute("community_road_maintain_reform_area");
            addValue(gbf.Repair_road_area_plan);
            result.Append(",");
            addAttribute("community_road_hardening_area");
            addValue(gbf.Harden_road_area_plan);
            result.Append(",");
            addAttribute("community_added_pavement_area");
            addValue(gbf.Add_sidewalk_plan);
            result.Append(",");
            addAttribute("community_pavement_colorful_brick_area");
            addValue(gbf.Change_sidewalk_plan);
            result.Append(",");
            addAttribute("community_added_water_supply_capa");
            addValue(gbf.Add_water_cap_plan);
            result.Append(",");
            addAttribute("community_added_water_supply_pre_facility");
            addValue(gbf.Add_water_press_plan);//todo
            result.Append(",");
            addAttribute("community_added_water_supply_pipe_len");
            addValue(gbf.Add_pipe_length_plan);
            result.Append(",");
            addAttribute("community_maintain_reform_water_pipe_len");
            addValue(gbf.Repair_pipe_length_plan);
            result.Append(",");
            addAttribute("community_water_meter_install_hou_num");
            addValue(gbf.Add_meter_plan);
            result.Append(",");
            addAttribute("community_added_transformer_capa_add");
            addValue(gbf.Repair_trans_plan);
            result.Append(",");
            addAttribute("community_added_transformer_capa_replace");
            addValue(gbf.Change_trans_plan);//todo
            result.Append(",");
            addAttribute("community_transformer_install_reform_num");
            addValue(gbf.Repair_trans_plan);//todo
            result.Append(",");
            addAttribute("community_added_distr_line_len");
            addValue(gbf.Add_line_plan);
            result.Append(",");
            addAttribute("community_maintain_reform_distr_line_len");
            addValue(gbf.Repair_line_plan);
            result.Append(",");
            addAttribute("community_ameter_install_hou_num");
            addValue(gbf.Install_trans_plan);
            result.Append(",");
            addAttribute("community_added_light_road_len");
            addValue(gbf.Add_out_light_plan);
            result.Append(",");
            addAttribute("community_repa_otd_light_facility_len");
            addValue(gbf.Repair_out_light_plan);
            result.Append(",");
            addAttribute("community_added_passageway_light_num");
            addValue(gbf.Add_in_light_plan);
            result.Append(",");
            addAttribute("community_repa_passageway_light_num");
            addValue(gbf.Repair_in_light_plan);
            result.Append(",");
            addAttribute("community_added_otd_ff_facility_num");
            addValue(gbf.Add_out_ff_plan);
            result.Append(",");
            addAttribute("community_added_ind_hydrant_num");
            addValue(gbf.Add_in_ff_plan);
            result.Append(",");
            addAttribute("community_ff_aisle_reform_len");
            addValue(gbf.Repair_exits_plan);
            result.Append("},");
            #endregion achievement
            addAttribute("achievement");
            #region
            result.Append("{");
            addAttribute("community_added_road_num");
            addValue(gbf.Add_line_com);
            result.Append(",");
            addAttribute("community_added_vehicles_road_area");
            addValue(gbf.Add_road_area_com);
            result.Append(",");
            addAttribute("community_road_maintain_reform_area");
            addValue(gbf.Repair_road_area_com);
            result.Append(",");
            addAttribute("community_road_hardening_area");
            addValue(gbf.Harden_road_area_com);
            result.Append(",");
            addAttribute("community_added_pavement_area");
            addValue(gbf.Add_sidewalk_com);
            result.Append(",");
            addAttribute("community_pavement_colorful_brick_area");
            addValue(gbf.Change_sidewalk_com);
            result.Append(",");
            addAttribute("community_added_water_supply_capa");
            addValue(gbf.Add_water_cap_com);
            result.Append(",");
            addAttribute("community_added_water_supply_pre_facility");
            addValue(gbf.Add_water_press_com);
            result.Append(",");
            addAttribute("community_added_water_supply_pipe_len");
            addValue(gbf.Add_pipe_length_com);
            result.Append(",");
            addAttribute("community_maintain_reform_water_pipe_len");
            addValue(gbf.Repair_pipe_length_com);
            result.Append(",");
            addAttribute("community_water_meter_install_hou_num");
            addValue(gbf.Add_meter_com);
            result.Append(",");
            addAttribute("community_added_transformer_capa_add");
            addValue(gbf.Repair_trans_com);
            result.Append(",");
            addAttribute("community_added_transformer_capa_replace");
            addValue(gbf.Change_trans_com);
            result.Append(",");
            addAttribute("community_transformer_install_reform_num");
            addValue(gbf.Repair_trans_com);
            result.Append(",");
            addAttribute("community_added_distr_line_len");
            addValue(gbf.Add_line_com);
            result.Append(",");
            addAttribute("community_maintain_reform_distr_line_len");
            addValue(gbf.Repair_pipe_length_com);
            result.Append(",");
            addAttribute("community_ameter_install_hou_num");
            addValue(gbf.Install_trans_com);
            result.Append(",");
            addAttribute("community_added_light_road_len");
            addValue(gbf.Add_out_light_com);
            result.Append(",");
            addAttribute("community_repa_otd_light_facility_len");
            addValue(gbf.Repair_out_light_com);
            result.Append(",");
            addAttribute("community_added_passageway_light_num");
            addValue(gbf.Add_in_light_com);
            result.Append(",");
            addAttribute("community_repa_passageway_light_num");
            addValue(gbf.Repair_in_light_com);
            result.Append(",");
            addAttribute("community_added_otd_ff_facility_num");
            addValue(gbf.Add_out_ff_com);
            result.Append(",");
            addAttribute("community_added_ind_hydrant_num");
            addValue(gbf.Add_in_ff_com);
            result.Append(",");
            addAttribute("community_ff_aisle_reform_len");
            addValue(gbf.Repair_exits_com);
            result.Append("}");
            #endregion
            result.Append("},");
            #endregion
            addAttribute("achievementSituation");
            #region achievementSituation
            result.Append("{");
            addAttribute("situation2013");
            #region
            result.Append("{");
            addAttribute("road_link_degree");
            addValue(gbf.Road_access_rate_2013);
            result.Append(",");
            addAttribute("road_good_degree");
            addValue(gbf.Road_clear_rate_2013);
            result.Append(",");
            addAttribute("water_capcity_degree");
            addValue(gbf.Water_supply_guar_rate_2013);
            result.Append(",");
            addAttribute("water_pipe_net_good_degree");
            addValue(gbf.Water_pipe_line_com_rate_2013);
            result.Append(",");
            addAttribute("one_hou_one_water_meter_rate");
            addValue(gbf.Water_double_one_rate_2013);
            result.Append(",");
            addAttribute("elec_capcity_degree");
            addValue(gbf.Elec_capa_guar_rate_2013);
            result.Append(",");
            addAttribute("elec_wire_safe_degree");
            addValue(gbf.Elec_line_safe_rate_2013);
            result.Append(",");
            addAttribute("one_hou_one_elec_meter_rate");
            addValue(gbf.Elec_double_one_rate_2013);
            result.Append(",");
            addAttribute("road_light_suff_degree");
            addValue(gbf.Out_light_com_rate_2013);
            result.Append(",");
            addAttribute("passway_light_suff_degree");
            addValue(gbf.In_light_com_rate_2013);
            result.Append(",");
            addAttribute("outdoors_ff_good_rate");
            addValue(gbf.Out_ff_com_rate_2013);
            result.Append(",");
            addAttribute("indoors_ff_good_rate");
            addValue(gbf.In_ff_com_rate_2013);
            result.Append(",");
            addAttribute("ff_way_good_rate");
            addValue(gbf.Ff_exits_com_rate_2013);
            result.Append("},");
            #endregion
            addAttribute("situationNow");
            #region
            result.Append("{");
            addAttribute("road_link_degree");
            addValue(gbf.Road_access_rate_now);
            result.Append(",");
            addAttribute("road_good_degree");
            addValue(gbf.Road_clear_rate_now);
            result.Append(",");
            addAttribute("water_capcity_degree");
            addValue(gbf.Water_supply_guar_rate_now);
            result.Append(",");
            addAttribute("water_pipe_net_good_degree");
            addValue(gbf.Water_pipe_line_com_rate_now);
            result.Append(",");
            addAttribute("one_hou_one_water_meter_rate");
            addValue(gbf.Water_double_one_rate_now);
            result.Append(",");
            addAttribute("elec_capcity_degree");
            addValue(gbf.Elec_capa_guar_rate_now);
            result.Append(",");
            addAttribute("elec_wire_safe_degree");
            addValue(gbf.Elec_line_safe_rate_now);
            result.Append(",");
            addAttribute("one_hou_one_elec_meter_rate");
            addValue(gbf.Elec_double_one_rate_now);
            result.Append(",");
            addAttribute("road_light_suff_degree");
            addValue(gbf.Out_light_com_rate_now);
            result.Append(",");
            addAttribute("passway_light_suff_degree");
            addValue(gbf.In_light_com_rate_now);
            result.Append(",");
            addAttribute("outdoors_ff_good_rate");
            addValue(gbf.Out_ff_com_rate_now);
            result.Append(",");
            addAttribute("indoors_ff_good_rate");
            addValue(gbf.In_ff_com_rate_now);
            result.Append(",");
            addAttribute("ff_way_good_rate");
            addValue(gbf.Ff_exits_com_rate_now);
            result.Append("}");
            #endregion
            result.Append("}");
            #endregion
            result.Append("}");
            return result.ToString();
        }

        public void addAttribute(String attr)
        {
            result.Append("\"" + attr + "\":");
        }


        public void addValue(String value)
        {
            if (value == null || value == "")
            {
                value = "--";
            }
            else
                result.Append("\"" + value + "\"");
        }

        public void addValue(double value)
        {
            if (value.ToString() == "非数字")
            {
                result.Append("--");
            }
            else
                result.Append("\"" + value.ToString("0.00") + "\"");
        }

        public void addValue(int value)
        {
            result.Append("\"" + value + "\"");
        }


    }
}