//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.subproject_physical_finish_situation {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtsubproject_id;
		protected global::System.Web.UI.WebControls.TextBox txtsubproject_no;
		protected global::System.Web.UI.WebControls.TextBox txtsubproject_name;
		protected global::System.Web.UI.WebControls.TextBox txtcounty_name;
		protected global::System.Web.UI.WebControls.TextBox txtproject_name;
		protected global::System.Web.UI.WebControls.TextBox txtsubproject_category;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity;
		protected global::System.Web.UI.WebControls.TextBox txtphysical_class;
		protected global::System.Web.UI.WebControls.TextBox txtphysical_subclass;
		protected global::System.Web.UI.WebControls.TextBox txtphysical_class_content;
		protected global::System.Web.UI.WebControls.TextBox txtplan_quantity;
		protected global::System.Web.UI.WebControls.TextBox txtnote_information;
		protected global::System.Web.UI.WebControls.TextBox txtstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txttciunset10;
		protected global::System.Web.UI.WebControls.TextBox txttciunset11;
		protected global::System.Web.UI.WebControls.TextBox txttciunset12;
		protected global::System.Web.UI.WebControls.TextBox txttciunset13;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
