//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.subproject_physical_finish_situation {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblsubproject_id;
	protected global::System.Web.UI.WebControls.Label lblsubproject_no;
	protected global::System.Web.UI.WebControls.Label lblsubproject_name;
	protected global::System.Web.UI.WebControls.Label lblcounty_name;
	protected global::System.Web.UI.WebControls.Label lblproject_name;
	protected global::System.Web.UI.WebControls.Label lblsubproject_category;
	protected global::System.Web.UI.WebControls.Label lblcommunity;
	protected global::System.Web.UI.WebControls.Label lblphysical_class;
	protected global::System.Web.UI.WebControls.Label lblphysical_subclass;
	protected global::System.Web.UI.WebControls.Label lblphysical_class_content;
	protected global::System.Web.UI.WebControls.Label lblplan_quantity;
	protected global::System.Web.UI.WebControls.Label lblnote_information;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbltciunset11;
	protected global::System.Web.UI.WebControls.Label lbltciunset12;
	protected global::System.Web.UI.WebControls.Label lbltciunset13;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;


       
    }
}
