//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_water_drain {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_drain_mechanism;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_domestic_sewage_consumption;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_drain_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_drain_main_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_drain_pipe_branch_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_drain_service_pipe_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_drain_canal_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_water_open_drain_canal_length;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_septic_tank_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_septic_tank_capacity;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcwdunset10;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
