//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_water_drain {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_drain_mechanism;
	protected global::System.Web.UI.WebControls.Label lblcommunity_domestic_sewage_consumption;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_drain_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_drain_main_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_drain_pipe_branch_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_drain_service_pipe_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_drain_canal_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_water_open_drain_canal_length;
	protected global::System.Web.UI.WebControls.Label lblcommunity_septic_tank_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_septic_tank_capacity;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset1;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset2;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset3;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset4;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset5;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset6;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset7;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset8;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset9;
	protected global::System.Web.UI.WebControls.Label lbltcwdunset10;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
