//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.subproject_project_associate {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblproject_id;
	protected global::System.Web.UI.WebControls.Label lblproject_name;
	protected global::System.Web.UI.WebControls.Label lblsubproject_name;
	protected global::System.Web.UI.WebControls.Label lblsubproject_id;


       
    }
}
