//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_management_responsible {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_address;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_manage_charge_person_name;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_manage_charge_person_telphone;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_monitor_charge_person_name;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_monitor_charge_person_telphone;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_contacts_telephone;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_staff_telephone;
		protected global::System.Web.UI.WebControls.TextBox txttcmrunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcmrunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcmrunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcmrunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcmrunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcmrunset6;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
