//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_management_responsible {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_address;
	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_manage_charge_person_name;
	protected global::System.Web.UI.WebControls.Label lblcommunity_manage_charge_person_telphone;
	protected global::System.Web.UI.WebControls.Label lblcommunity_monitor_charge_person_name;
	protected global::System.Web.UI.WebControls.Label lblcommunity_monitor_charge_person_telphone;
	protected global::System.Web.UI.WebControls.Label lblcommunity_contacts_telephone;
	protected global::System.Web.UI.WebControls.Label lblcommunity_staff_telephone;
	protected global::System.Web.UI.WebControls.Label lbltcmrunset1;
	protected global::System.Web.UI.WebControls.Label lbltcmrunset2;
	protected global::System.Web.UI.WebControls.Label lbltcmrunset3;
	protected global::System.Web.UI.WebControls.Label lbltcmrunset4;
	protected global::System.Web.UI.WebControls.Label lbltcmrunset5;
	protected global::System.Web.UI.WebControls.Label lbltcmrunset6;


       
    }
}
