//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_water_drain_problem {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fill_type;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pipe_no_reasonable_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_form_warea_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_form_warea_affect_res_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_not_access_uspn_res_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_not_access_uspn_house_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_insuf_pipe_size_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pipe_aging_corrosion_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pipe_damage_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_septic_small_volume_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_septic_damage_leaking_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_sewage_straight_to_cj_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_gutter_damage;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_insuf_gutter;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txttciunset1;
		protected global::System.Web.UI.WebControls.TextBox txttciunset2;
		protected global::System.Web.UI.WebControls.TextBox txttciunset3;
		protected global::System.Web.UI.WebControls.TextBox txttciunset4;
		protected global::System.Web.UI.WebControls.TextBox txttciunset5;
		protected global::System.Web.UI.WebControls.TextBox txttciunset6;
		protected global::System.Web.UI.WebControls.TextBox txttciunset7;
		protected global::System.Web.UI.WebControls.TextBox txttciunset8;
		protected global::System.Web.UI.WebControls.TextBox txttciunset9;
		protected global::System.Web.UI.WebControls.TextBox txttciunset10;
		protected global::System.Web.UI.WebControls.TextBox txttciunset11;
		protected global::System.Web.UI.WebControls.TextBox txttciunset12;
		protected global::System.Web.UI.WebControls.TextBox txttciunset13;
		protected global::System.Web.UI.WebControls.TextBox txttciunset14;
		protected global::System.Web.UI.WebControls.TextBox txttciunset15;
		protected global::System.Web.UI.WebControls.TextBox txttciunset16;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_pipe_damage_length;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
