//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_water_drain_problem {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_fill_type;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pipe_no_reasonable_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_form_warea_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_form_warea_affect_res_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_not_access_uspn_res_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_not_access_uspn_house_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_insuf_pipe_size_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pipe_aging_corrosion_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pipe_damage_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_septic_small_volume_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_septic_damage_leaking_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_sewage_straight_to_cj_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_gutter_damage;
	protected global::System.Web.UI.WebControls.Label lblcommunity_insuf_gutter;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbltciunset1;
	protected global::System.Web.UI.WebControls.Label lbltciunset2;
	protected global::System.Web.UI.WebControls.Label lbltciunset3;
	protected global::System.Web.UI.WebControls.Label lbltciunset4;
	protected global::System.Web.UI.WebControls.Label lbltciunset5;
	protected global::System.Web.UI.WebControls.Label lbltciunset6;
	protected global::System.Web.UI.WebControls.Label lbltciunset7;
	protected global::System.Web.UI.WebControls.Label lbltciunset8;
	protected global::System.Web.UI.WebControls.Label lbltciunset9;
	protected global::System.Web.UI.WebControls.Label lbltciunset10;
	protected global::System.Web.UI.WebControls.Label lbltciunset11;
	protected global::System.Web.UI.WebControls.Label lbltciunset12;
	protected global::System.Web.UI.WebControls.Label lbltciunset13;
	protected global::System.Web.UI.WebControls.Label lbltciunset14;
	protected global::System.Web.UI.WebControls.Label lbltciunset15;
	protected global::System.Web.UI.WebControls.Label lbltciunset16;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcommunity_pipe_damage_length;


       
    }
}
