//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_lf_employment {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_total_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_student_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_age_bet_16_and_29_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_age_bet_30_and_39_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_age_bet_40_and_49_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_age_larger_than_50_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_illiterate_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_primary_school_education_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_middle_school_education_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_senior_school_education_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_college_graduate_lf_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_average_education_year;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_with_no_skill_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_with_junior_skill_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_with_medium_grade_skill_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_with_senior_skill_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_hou_with_no_job_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_immigrant_hou_with_no_job_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_lf_having_a_job_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_ai_employee_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_enterprise_employee_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_part_time_job_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_migrant_workers_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_household_management_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_no_job_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_have_job_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_farmer_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_industrial_employment_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_buil_industrial_employment_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_transport_employment_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_whs_and_retail_employment_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_catering_accomm_employment_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_other_service_employment_pop;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_empm_information_platform;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_entp_supportive_policy;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_enp_supportive_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_public_spirited_job_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset7;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset8;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset9;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset10;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset11;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset12;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset13;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset14;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset15;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset16;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset17;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset18;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset19;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset20;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset21;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset22;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset23;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset24;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset25;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset26;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset27;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset28;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset29;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset30;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset31;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset32;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset33;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset34;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset35;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset36;
		protected global::System.Web.UI.WebControls.TextBox txttcleunset37;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
