//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_lf_employment {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_total_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_student_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_age_bet_16_and_29_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_age_bet_30_and_39_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_age_bet_40_and_49_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_age_larger_than_50_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_illiterate_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_primary_school_education_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_middle_school_education_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_senior_school_education_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_college_graduate_lf_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_average_education_year;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_with_no_skill_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_with_junior_skill_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_with_medium_grade_skill_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_with_senior_skill_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_hou_with_no_job_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_immigrant_hou_with_no_job_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_lf_having_a_job_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_ai_employee_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_enterprise_employee_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_part_time_job_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_migrant_workers_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_household_management_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_no_job_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_have_job_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_farmer_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_industrial_employment_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_buil_industrial_employment_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_transport_employment_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_whs_and_retail_employment_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_catering_accomm_employment_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_other_service_employment_pop;
	protected global::System.Web.UI.WebControls.Label lblcommunity_empm_information_platform;
	protected global::System.Web.UI.WebControls.Label lblcommunity_entp_supportive_policy;
	protected global::System.Web.UI.WebControls.Label lblcommunity_enp_supportive_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_public_spirited_job_num;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcleunset1;
	protected global::System.Web.UI.WebControls.Label lbltcleunset2;
	protected global::System.Web.UI.WebControls.Label lbltcleunset3;
	protected global::System.Web.UI.WebControls.Label lbltcleunset4;
	protected global::System.Web.UI.WebControls.Label lbltcleunset5;
	protected global::System.Web.UI.WebControls.Label lbltcleunset6;
	protected global::System.Web.UI.WebControls.Label lbltcleunset7;
	protected global::System.Web.UI.WebControls.Label lbltcleunset8;
	protected global::System.Web.UI.WebControls.Label lbltcleunset9;
	protected global::System.Web.UI.WebControls.Label lbltcleunset10;
	protected global::System.Web.UI.WebControls.Label lbltcleunset11;
	protected global::System.Web.UI.WebControls.Label lbltcleunset12;
	protected global::System.Web.UI.WebControls.Label lbltcleunset13;
	protected global::System.Web.UI.WebControls.Label lbltcleunset14;
	protected global::System.Web.UI.WebControls.Label lbltcleunset15;
	protected global::System.Web.UI.WebControls.Label lbltcleunset16;
	protected global::System.Web.UI.WebControls.Label lbltcleunset17;
	protected global::System.Web.UI.WebControls.Label lbltcleunset18;
	protected global::System.Web.UI.WebControls.Label lbltcleunset19;
	protected global::System.Web.UI.WebControls.Label lbltcleunset20;
	protected global::System.Web.UI.WebControls.Label lbltcleunset21;
	protected global::System.Web.UI.WebControls.Label lbltcleunset22;
	protected global::System.Web.UI.WebControls.Label lbltcleunset23;
	protected global::System.Web.UI.WebControls.Label lbltcleunset24;
	protected global::System.Web.UI.WebControls.Label lbltcleunset25;
	protected global::System.Web.UI.WebControls.Label lbltcleunset26;
	protected global::System.Web.UI.WebControls.Label lbltcleunset27;
	protected global::System.Web.UI.WebControls.Label lbltcleunset28;
	protected global::System.Web.UI.WebControls.Label lbltcleunset29;
	protected global::System.Web.UI.WebControls.Label lbltcleunset30;
	protected global::System.Web.UI.WebControls.Label lbltcleunset31;
	protected global::System.Web.UI.WebControls.Label lbltcleunset32;
	protected global::System.Web.UI.WebControls.Label lbltcleunset33;
	protected global::System.Web.UI.WebControls.Label lbltcleunset34;
	protected global::System.Web.UI.WebControls.Label lbltcleunset35;
	protected global::System.Web.UI.WebControls.Label lbltcleunset36;
	protected global::System.Web.UI.WebControls.Label lbltcleunset37;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
