//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.Community_Base {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_name;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_location;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_county;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_type;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_feature;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_function_area;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_function_type;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_county;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_street_committees;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_main_business_area;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_main_education_area;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_railway_station;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_coach_station;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_passenger_quay;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_main_street;
		protected global::System.Web.UI.WebControls.TextBox txtdistance_to_collector_street;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset1;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset2;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset3;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset4;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset5;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset6;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset7;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset8;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset9;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset10;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset11;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset12;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset13;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset14;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset15;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset16;
		protected global::System.Web.UI.WebControls.TextBox txttbcunset17;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_wcommunity;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_category;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_construct_year;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_province;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
