//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.Community_Base {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_name;
	protected global::System.Web.UI.WebControls.Label lblcommunity_location;
	protected global::System.Web.UI.WebControls.Label lblcommunity_county;
	protected global::System.Web.UI.WebControls.Label lblcommunity_type;
	protected global::System.Web.UI.WebControls.Label lblcommunity_feature;
	protected global::System.Web.UI.WebControls.Label lblcommunity_function_area;
	protected global::System.Web.UI.WebControls.Label lblcommunity_function_type;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_county;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_street_committees;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_main_business_area;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_main_education_area;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_railway_station;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_coach_station;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_passenger_quay;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_main_street;
	protected global::System.Web.UI.WebControls.Label lbldistance_to_collector_street;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltbcunset1;
	protected global::System.Web.UI.WebControls.Label lbltbcunset2;
	protected global::System.Web.UI.WebControls.Label lbltbcunset3;
	protected global::System.Web.UI.WebControls.Label lbltbcunset4;
	protected global::System.Web.UI.WebControls.Label lbltbcunset5;
	protected global::System.Web.UI.WebControls.Label lbltbcunset6;
	protected global::System.Web.UI.WebControls.Label lbltbcunset7;
	protected global::System.Web.UI.WebControls.Label lbltbcunset8;
	protected global::System.Web.UI.WebControls.Label lbltbcunset9;
	protected global::System.Web.UI.WebControls.Label lbltbcunset10;
	protected global::System.Web.UI.WebControls.Label lbltbcunset11;
	protected global::System.Web.UI.WebControls.Label lbltbcunset12;
	protected global::System.Web.UI.WebControls.Label lbltbcunset13;
	protected global::System.Web.UI.WebControls.Label lbltbcunset14;
	protected global::System.Web.UI.WebControls.Label lbltbcunset15;
	protected global::System.Web.UI.WebControls.Label lbltbcunset16;
	protected global::System.Web.UI.WebControls.Label lbltbcunset17;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcommunity_wcommunity;
	protected global::System.Web.UI.WebControls.Label lblcommunity_category;
	protected global::System.Web.UI.WebControls.Label lblcommunity_construct_year;
	protected global::System.Web.UI.WebControls.Label lblcommunity_province;


       
    }
}
