//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_light {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_streetlight_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_energy_efficient_streetlight_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_good_streetlight_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_otd_exercise_yard_light_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_otd_good_exercise_yard_light_rate;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_passageway_light_num;
		protected global::System.Web.UI.WebControls.TextBox txtcommunity_good_passageway_light_rate;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
		protected global::System.Web.UI.WebControls.TextBox txttcltunset1;
		protected global::System.Web.UI.WebControls.TextBox txttcltunset2;
		protected global::System.Web.UI.WebControls.TextBox txttcltunset3;
		protected global::System.Web.UI.WebControls.TextBox txttcltunset4;
		protected global::System.Web.UI.WebControls.TextBox txttcltunset5;
		protected global::System.Web.UI.WebControls.TextBox txttcltunset6;
		protected global::System.Web.UI.WebControls.TextBox txttcltunset7;
		protected global::System.Web.UI.WebControls.TextBox txtlock_tables;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
