//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTG.Web.TTGWeb.community_light {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommunity_id;
	protected global::System.Web.UI.WebControls.Label lblcommunity_streetlight_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_energy_efficient_streetlight_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_good_streetlight_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_otd_exercise_yard_light_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_otd_good_exercise_yard_light_rate;
	protected global::System.Web.UI.WebControls.Label lblcommunity_passageway_light_num;
	protected global::System.Web.UI.WebControls.Label lblcommunity_good_passageway_light_rate;
	protected global::System.Web.UI.WebControls.Label lblstatistics_date;
	protected global::System.Web.UI.WebControls.Label lbltcltunset1;
	protected global::System.Web.UI.WebControls.Label lbltcltunset2;
	protected global::System.Web.UI.WebControls.Label lbltcltunset3;
	protected global::System.Web.UI.WebControls.Label lbltcltunset4;
	protected global::System.Web.UI.WebControls.Label lbltcltunset5;
	protected global::System.Web.UI.WebControls.Label lbltcltunset6;
	protected global::System.Web.UI.WebControls.Label lbltcltunset7;
	protected global::System.Web.UI.WebControls.Label lbllock_tables;
	protected global::System.Web.UI.WebControls.Label lblcheck_status;


       
    }
}
